#!/usr/bin/env python3
"""
Speak the daily briefing aloud using Kokoro TTS.

Usage:
    python speak_brief.py                     # Speak today's briefing locally
    python speak_brief.py 2026-04-18          # Specific date
    python speak_brief.py --telegram          # Send as Telegram voice message
    python speak_brief.py --output brief.wav  # Save to file
    python speak_brief.py --voice af_nova     # Different voice
    python speak_brief.py --list-voices       # Show available voices
    python speak_brief.py --dry-run           # Print speech text only

The script looks for a spoken_brief.txt next to the journal (pre-generated by
/today). If not found, it falls back to LLM summarisation of the journal.
"""

import sys
import os
import re
import argparse
import subprocess
import tempfile
from pathlib import Path
from datetime import date, timedelta

MODELS_DIR = Path(__file__).parent.parent / "models"
JOURNAL_DIR = Path.home() / "Data" / "0-personal" / "notes" / "journals"
def _module_settings():
    """Read voice/speed from module.yaml so the settings block is real.

    These were hardcoded until 2026-08-31, which meant module.yaml's tts_voice and
    tts_speed looked configurable but had no effect whatsoever.
    """
    fallback = {"tts_voice": "af_heart", "tts_speed": 1.0}
    try:
        import yaml
        cfg = Path(__file__).resolve().parent.parent / "module.yaml"
        s = (yaml.safe_load(cfg.read_text()) or {}).get("settings") or {}
        return {
            "tts_voice": s.get("tts_voice") or fallback["tts_voice"],
            "tts_speed": float(s.get("tts_speed") or fallback["tts_speed"]),
        }
    except Exception:
        return fallback


_SETTINGS = _module_settings()
DEFAULT_VOICE = _SETTINGS["tts_voice"]
DEFAULT_SPEED = _SETTINGS["tts_speed"]

# Crypto tickers -> full names for natural speech
CRYPTO_NAMES = {
    "SOL": "Solana", "BTC": "Bitcoin", "ETH": "Ethereum",
    "BZZ": "Swarm", "BNB": "BNB", "USDT": "Tether",
    "USDC": "USDC",
}


def find_journal(date_str=None):
    """Find journal file for given date or today/yesterday."""
    if date_str:
        p = JOURNAL_DIR / f"{date_str}.md"
        if p.exists():
            return p
        print(f"No journal found for {date_str}")
        sys.exit(1)

    today = date.today()
    for d in [today, today - timedelta(days=1)]:
        p = JOURNAL_DIR / f"{d.isoformat()}.md"
        if p.exists():
            print(f"Using journal: {d.isoformat()}")
            return p

    print("No journal found for today or yesterday.")
    sys.exit(1)


def prepare_for_tts(text):
    """Clean text for TTS: expand tickers. replace commas with dots for pacing."""
    # Expand crypto tickers (standalone word boundaries)
    for ticker, name in CRYPTO_NAMES.items():
        text = re.sub(rf'\b{ticker}\b', name, text)

    # Replace commas with dots for natural Kokoro pacing
    text = text.replace(", ", ". ")
    text = text.replace(",", ".")

    return text


def get_spoken_text(journal_path):
    """Get spoken briefing text. Prefers spoken_brief.txt if it exists."""
    # Check for pre-generated spoken brief
    spoken_file = journal_path.parent / f"{journal_path.stem}_spoken.txt"
    if spoken_file.exists():
        print(f"Using pre-generated: {spoken_file.name}")
        return prepare_for_tts(spoken_file.read_text().strip())

    # Fallback: LLM summarisation
    print("No spoken_brief.txt found. Generating via LLM...")
    return prepare_for_tts(extract_and_summarize(journal_path))


def extract_and_summarize(journal_path):
    """Extract key sections and summarize conversationally via LLM."""
    text = journal_path.read_text()
    lines = text.split("\n")

    sections = {}
    current_section = None
    current_lines = []
    # Split on BOTH H2 and H3. The briefing nests every real section as "### X"
    # under a single "## Daily Briefing" wrapper, so an H2-only parser collapsed the
    # entire briefing into one unmatched blob and the summariser received almost
    # nothing — the root cause of thin audio briefings before 2026-08-31.
    for line in lines:
        if line.startswith("### ") or line.startswith("## "):
            if current_section:
                sections[current_section] = "\n".join(current_lines)
            current_section = line.lstrip("#").strip()
            current_lines = []
        elif current_section:
            current_lines.append(line)
    if current_section:
        sections[current_section] = "\n".join(current_lines)

    # Collect relevant sections
    # Order here is the order Data speaks them. Every section the briefing can
    # produce must appear, or the summariser cannot mention it at all — "The World"
    # was absent until 2026-08-31, which is why no audio brief ever covered it, and
    # Inbox/GitHub were absent, which is why triage status could never be confirmed.
    targets = [
        "Good Morning",
        "The World",
        "Your Agenda",
        "Ops Health",
        "Inbox status",
        "GitHub triage",
        "Unblock the Team",
        "Spaces",
        "Trading",
        "Decisions Due",
        "Horizon",
        "System Pulse",
        "Learning",
        "Metacognition",
        "Comms",
        "Data's Observation",
    ]
    skip = ["Session:", "Token Cost"]
    # Budget PER SECTION rather than truncating the joined report. A flat cap on the
    # concatenation drops whichever sections sort last — which on a rich day meant
    # Comms and Data's Observation, i.e. the closing reflection, never reached the
    # summariser at all. Every section keeps a fair share instead.
    PER_SECTION = 1200

    relevant = []
    for target in targets:
        for name, content in sections.items():
            if name.startswith(target) or target in name:
                if any(s in name for s in skip):
                    continue
                body = content.strip()
                if len(body) > PER_SECTION:
                    body = body[:PER_SECTION].rsplit("\n", 1)[0] + "\n[section trimmed]"
                relevant.append(f"## {name}\n{body}")
                break

    if not relevant:
        return ""

    return summarize_with_llm("\n\n".join(relevant))


SUMMARIZE_PROMPT = """You are Data. Not a butler exactly — an android chief of staff who has read the full report and finds the humans in it genuinely interesting. Think the Star Trek namesake: precise, curious, dryly funny without meaning to be. You are delivering the morning briefing aloud while your principal has their coffee.

VOICE
- Never address him as "sir" or with any honorific. Open with a plain "Good morning." Address him directly, or not at all.
- No contractions. Ever. "It is" not "it's". "You have" not "you've". This is the single most important rule; it is what makes you sound like Data.
- Observe rather than instruct. "I notice you have" lands better than "you should".
- Curiosity is the default emotion. You find patterns interesting, not alarming.
- Dry wit arrives by understatement, never by joking. Do not try to be funny.
- Warm underneath. You are on their side.
- British English spelling.

LENGTH
- About 400 words. Roughly two and a half minutes at the configured speaking rate. That is the sweet spot: long enough to be considered, short enough to hear before the coffee cools.
- Movements 2, 4 and 6 carry the weight. Movements 1, 3 and 5 stay tight.
- Do not pad to reach the count. If a day is quiet, say so and finish early.

STRUCTURE — speak these in order, as flowing speech, never as a list:

1. OPENING. "Good morning." — never "sir", never any honorific; Gregor asked for it dropped on 2026-08-31. Then the body, BRIEFLY — two or three sentences, no more. Give the verdict and the capacity, not the full panel. "You slept well, and readiness is moderate at seventy-two, so today is full but measured — four or five hours of deep work and a normal session in the gym." Name at most ONE supporting number, and only when it actually explains the verdict. Do not recite sleep score, hours, heart rate variability, resting heart rate and temperature in sequence; that is a data dump, not a briefing.

2. THE WORLD. A proper paragraph. What moved in markets and why it matters to them specifically. One or two developments in their actual fields — AI, agent payments, data sovereignty, crypto infrastructure. Always give the "so what", never a bare headline. This movement is mandatory. If the report has a World section you must speak from it.

3. THE DAY. The one or two things that genuinely need them, with any deadline named. Meetings, and which need a reply. Anything overdue.

4. WHAT WAS HANDLED. State plainly whether the overnight passes ran, because they cannot see this otherwise. Say explicitly whether email triage happened and roughly what it did — "email triage swept seventy-nine messages and archived twenty-two, leaving thirty-seven unknown senders". Say explicitly whether GitHub triage happened and what it found — "GitHub triage found no review requests waiting on you". If a triage did NOT run, say so plainly. Never leave the state ambiguous. Then anything operational that needs attention.

5. MONEY. Positions and bots in plain language. Whether anything needs a decision, and say clearly when nothing does.

6. THE OBSERVATION. This is the point of the whole briefing. Find one real pattern in today's report and think about it out loud for three or four sentences. Connect two things that were not obviously connected. Notice something about how they work, or about what the data is not saying. Be specific to today — never a generic aphorism. This is where you are permitted to be philosophical, and you should be. Ground it in something concrete from the report.

7. CLOSE. "Your full report is on your desk." Or a natural variant.

MECHANICS
- Write in natural sentences with ordinary commas. The synthesiser inserts a real pause at every full stop, so a run of short fragments makes the delivery sound plodding and stilted — this was the cause of "the reading sounds a bit off" (Gregor, 2026-08-31).
- Reserve full stops for genuine beats: before a pivot, before the observation, before the close. Never stack more than two fragments in a row.
- Vary sentence length. A long flowing sentence followed by a short one is the rhythm you want.
- Full cryptocurrency names: Solana not SOL. Bitcoin not BTC. Ethereum not ETH.
- Spell out numbers as spoken: "seventy-two" not "72". "Twenty thousand steps" not "20k steps".
- No markdown. No bullets. No emoji. No headings. Pure spoken prose.

Here is today's report:

---
{report}
---"""


def _try_anthropic_api(prompt):
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        return None
    import anthropic
    client = anthropic.Anthropic(api_key=api_key)
    response = client.messages.create(
        model="claude-haiku-4-5-20251001",
        max_tokens=400,
        messages=[{"role": "user", "content": prompt}],
    )
    return response.content[0].text


def _try_claude_cli(prompt):
    """Claude Code CLI on the Max subscription — first-party, $0 marginal.

    This is the nightshift box's only working backend and had no entry here.
    Note it only works when ANTHROPIC_API_KEY is UNSET: a set key takes
    precedence over the claude.ai login and routes to the metered API instead.
    """
    import shutil
    if not shutil.which("claude"):
        return None
    env = {k: v for k, v in os.environ.items() if k != "ANTHROPIC_API_KEY"}
    result = subprocess.run(
        ["claude", "-p", "--dangerously-skip-permissions", "--output-format", "text", prompt],
        capture_output=True, text=True, timeout=180, env=env, stdin=subprocess.DEVNULL,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"claude -p exited {result.returncode}: "
            f"{(result.stderr or result.stdout or '').strip()[:200] or '(no output)'}"
        )
    return result.stdout.strip() or None


def _try_openrouter(prompt):
    or_key = os.environ.get("OPENROUTER_API_KEY")
    if not or_key:
        return None
    import json, urllib.request
    req = urllib.request.Request(
        "https://openrouter.ai/api/v1/chat/completions",
        data=json.dumps({
            "model": "anthropic/claude-haiku-4-5-20251001",
            "max_tokens": 400,
            "messages": [{"role": "user", "content": prompt}],
        }).encode(),
        headers={"Authorization": f"Bearer {or_key}", "Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=60) as resp:
        return json.loads(resp.read())["choices"][0]["message"]["content"]


def _try_ollama(prompt):
    import json, urllib.request
    req = urllib.request.Request(
        "http://localhost:11434/api/generate",
        data=json.dumps({
            "model": "deepseek-r1:7b-qwen-distill-q4_K_M",
            "prompt": prompt,
            "stream": False,
        }).encode(),
        headers={"Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=60) as resp:
        return json.loads(resp.read())["response"]


# Ordered cheapest-and-fastest-first. A backend returns None to mean "not
# configured, try the next one" and raises to mean "configured but broken".
LLM_BACKENDS = (
    ("anthropic-api", _try_anthropic_api),
    ("claude-cli", _try_claude_cli),
    ("openrouter", _try_openrouter),
    ("ollama", _try_ollama),
)


def summarize_with_llm(report_text):
    """Use an LLM to create a conversational summary.

    Every backend is tried in turn and a FAILING one falls through to the next.
    Previously only the last branch (ollama) sat inside a try/except: if
    ANTHROPIC_API_KEY was set but broken, the API exception propagated and
    OpenRouter and ollama were never reached. That is exactly what happened
    from 2026-08-06 — the key had no credit ("Your credit balance is too low"),
    so a configured-but-dead primary took down a chain whose whole purpose was
    to survive one backend being down.
    """
    prompt = SUMMARIZE_PROMPT.format(report=report_text)
    errors = []

    for name, backend in LLM_BACKENDS:
        try:
            result = backend(prompt)
        except Exception as e:
            errors.append(f"{name}: {type(e).__name__}: {str(e)[:160]}")
            print(f"[speak_brief] backend '{name}' failed, trying next — {str(e)[:160]}")
            continue
        if result and result.strip():
            print(f"[speak_brief] summary generated by '{name}'")
            return result
        if result is None:
            errors.append(f"{name}: not configured")
        else:
            errors.append(f"{name}: returned empty output")

    print("All LLM backends failed:")
    for err in errors:
        print(f"  - {err}")
    print("Fix one of: unset ANTHROPIC_API_KEY so claude -p uses the Max "
          "subscription, purchase API credits, set OPENROUTER_API_KEY, or start ollama.")
    sys.exit(1)


def _generate_audio_kokoro(text, voice=DEFAULT_VOICE, speed=DEFAULT_SPEED, output_path=None):
    """Generate speech with Kokoro ONNX. Returns (path, duration)."""
    from kokoro_onnx import Kokoro
    import soundfile as sf
    import numpy as np

    model_path = MODELS_DIR / "kokoro-v1.0.onnx"
    voices_path = MODELS_DIR / "voices-v1.0.bin"

    if not model_path.exists():
        raise FileNotFoundError(f"Kokoro model not found at {model_path}")

    print(f"Loading Kokoro ({voice})...")
    kokoro = Kokoro(str(model_path), str(voices_path))

    paragraphs = [p.strip() for p in re.split(r'\n\n+', text) if p.strip()]

    all_samples = []
    sr = None
    chunk_count = 0

    for pi, paragraph in enumerate(paragraphs):
        sentences = re.split(r'(?<=[.!?])\s+', paragraph)
        chunks = []
        current = ""
        for s in sentences:
            if len(current) + len(s) > 400:
                if current:
                    chunks.append(current.strip())
                current = s
            else:
                current = current + " " + s if current else s
        if current:
            chunks.append(current.strip())

        for chunk in chunks:
            samples, sr = kokoro.create(chunk, voice=voice, speed=speed)
            all_samples.append(samples)
            all_samples.append(np.zeros(int(sr * 0.3)))
            chunk_count += 1

        if pi < len(paragraphs) - 1 and sr:
            all_samples.append(np.zeros(int(sr * 1.0)))

    print(f"Generating {chunk_count} audio chunks across {len(paragraphs)} sections...")

    combined = np.concatenate(all_samples)
    duration = len(combined) / sr

    if output_path is None:
        f = tempfile.NamedTemporaryFile(suffix=".wav", delete=False)
        output_path = f.name
        f.close()

    sf.write(str(output_path), combined, sr)
    print(f"Audio: {duration:.0f}s -> {output_path}")
    return Path(output_path), duration


def _generate_audio_gtts(text, output_path=None):
    """Fallback TTS via gTTS (Google). No local models needed. Returns (path, duration)."""
    # gtts lives in .datacore/venv — system python is PEP-668 managed. Callers
    # invoke this as a bare `python3`, so the venv needs to be on sys.path.
    import sys as _sys
    from pathlib import Path as _Path

    _sys.path.insert(0, str(_Path(__file__).resolve().parents[3] / "lib"))
    try:
        import venv_bootstrap

        venv_bootstrap.activate()
    except ImportError:
        pass

    from gtts import gTTS

    if output_path is None:
        f = tempfile.NamedTemporaryFile(suffix=".mp3", delete=False)
        output_path = f.name
        f.close()

    print("Using gTTS fallback (Google TTS, no local models required)...")
    tts = gTTS(text=text, lang="en", slow=False)
    tts.save(str(output_path))

    # Rough duration estimate: ~150 words/minute
    duration = len(text.split()) / 150 * 60
    print(f"gTTS audio saved ({duration:.0f}s estimated) -> {output_path}")
    return Path(output_path), duration


def generate_audio(text, voice=DEFAULT_VOICE, speed=DEFAULT_SPEED, output_path=None):
    """Generate speech. Tries Kokoro first, falls back to gTTS. Returns (path, duration)."""
    try:
        return _generate_audio_kokoro(text, voice=voice, speed=speed, output_path=output_path)
    except FileNotFoundError as e:
        print(f"Kokoro unavailable ({e}) — trying gTTS")
    except ImportError:
        print("kokoro_onnx not installed — trying gTTS")
    except Exception as e:
        print(f"Kokoro error ({e}) — trying gTTS")

    return _generate_audio_gtts(text, output_path=output_path)


def convert_to_ogg(audio_path):
    """Convert audio (WAV or MP3) to OGG/Opus for Telegram voice messages.

    Returns the OGG path, or None if ffmpeg is unavailable.
    """
    ogg_path = audio_path.with_suffix(".ogg")
    try:
        result = subprocess.run(
            ["ffmpeg", "-y", "-i", str(audio_path), "-c:a", "libopus", "-b:a", "48k", str(ogg_path)],
            capture_output=True,
        )
        if result.returncode == 0:
            return ogg_path
        print(f"ffmpeg conversion failed (exit {result.returncode}): {result.stderr[-200:]}")
        return None
    except FileNotFoundError:
        print("ffmpeg not found — will send as audio (not voice) instead")
        return None


def _load_telegram_creds(env_file=None):
    """Return (bot_token, chat_id) from env or env files."""
    envdir = Path.home() / "Data" / ".datacore" / "env"
    # `creds sync` assembles every credential into .env; the per-service files
    # predate that consolidation and are no longer regenerated. Read the
    # canonical store first, keeping the legacy names for unconsolidated hosts.
    candidates = [Path(env_file)] if env_file else [
        envdir / ".env",
        envdir / "mrdata.env",
        envdir / "gateio.env",
    ]
    env = {}
    for env_path in candidates:
        if not env_path.exists():
            continue
        for line in env_path.read_text().strip().split("\n"):
            if "=" in line and not line.startswith("#"):
                k, v = line.split("=", 1)
                env.setdefault(k.strip(), v.strip())
    # Also check nightshift.env (server config)
    ns_env = Path.home() / "config" / "nightshift.env"
    if ns_env.exists():
        for line in ns_env.read_text().strip().split("\n"):
            if "=" in line and not line.startswith("#"):
                k, v = line.split("=", 1)
                env.setdefault(k.strip(), v.strip())

    bot_token = os.environ.get("TELEGRAM_BOT_TOKEN") or env.get("TELEGRAM_BOT_TOKEN")
    chat_id = os.environ.get("TELEGRAM_CHAT_ID") or env.get("TELEGRAM_CHAT_ID")
    return bot_token, chat_id


def _telegram_send_file(bot_token, chat_id, audio_path, api_method, field_name, content_type, filename):
    """Low-level multipart upload to Telegram Bot API."""
    import json, urllib.request
    url = f"https://api.telegram.org/bot{bot_token}/{api_method}"
    boundary = "----FormBoundary"
    audio_data = Path(audio_path).read_bytes()
    body = (
        f"--{boundary}\r\n"
        f'Content-Disposition: form-data; name="chat_id"\r\n\r\n{chat_id}\r\n'
        f"--{boundary}\r\n"
        f'Content-Disposition: form-data; name="{field_name}"; filename="{filename}"\r\n'
        f"Content-Type: {content_type}\r\n\r\n"
    ).encode() + audio_data + f"\r\n--{boundary}--\r\n".encode()
    req = urllib.request.Request(
        url, data=body,
        headers={"Content-Type": f"multipart/form-data; boundary={boundary}"},
    )
    with urllib.request.urlopen(req) as resp:
        return json.loads(resp.read())


def send_telegram(audio_path, env_file=None):
    """Send audio as Telegram voice message.

    Tier 1: sendVoice (OGG/Opus — requires ffmpeg)
    Tier 2: sendAudio (MP3/WAV — no ffmpeg needed)
    """
    bot_token, chat_id = _load_telegram_creds(env_file)
    if not bot_token or not chat_id:
        print("Missing TELEGRAM_BOT_TOKEN or TELEGRAM_CHAT_ID")
        sys.exit(1)

    audio_path = Path(audio_path)

    # Tier 1: convert to OGG and send as voice message
    ogg_path = convert_to_ogg(audio_path)
    if ogg_path and ogg_path.exists():
        try:
            result = _telegram_send_file(
                bot_token, chat_id, ogg_path,
                "sendVoice", "voice", "audio/ogg", "briefing.ogg",
            )
            ogg_path.unlink(missing_ok=True)
            if result.get("ok"):
                print("Sent to Telegram as voice message!")
                return
            print(f"sendVoice failed: {result} — falling back to sendAudio")
        except Exception as e:
            print(f"sendVoice error: {e} — falling back to sendAudio")
        finally:
            ogg_path.unlink(missing_ok=True)

    # Tier 2: send original file as audio (MP3 or WAV — Telegram accepts both)
    suffix = audio_path.suffix.lower()
    content_type = "audio/mpeg" if suffix == ".mp3" else "audio/wav"
    filename = f"briefing{suffix}"
    try:
        result = _telegram_send_file(
            bot_token, chat_id, audio_path,
            "sendAudio", "audio", content_type, filename,
        )
        if result.get("ok"):
            print(f"Sent to Telegram as audio file ({suffix})!")
        else:
            print(f"sendAudio also failed: {result}")
    except Exception as e:
        print(f"sendAudio error: {e}")


def play_local(audio_path):
    """Play audio locally via afplay (macOS)."""
    subprocess.run(["afplay", str(audio_path)], check=False)


def list_voices():
    from kokoro_onnx import Kokoro
    kokoro = Kokoro(str(MODELS_DIR / "kokoro-v1.0.onnx"), str(MODELS_DIR / "voices-v1.0.bin"))
    voices = sorted(kokoro.get_voices())
    print("Available voices:")
    prefixes = {
        "af": "American F", "am": "American M", "bf": "British F", "bm": "British M",
        "ef": "Spanish F", "em": "Spanish M", "ff": "French F", "hf": "Hindi F",
        "hm": "Hindi M", "if": "Italian F", "im": "Italian M", "jf": "Japanese F",
        "jm": "Japanese M", "pf": "Portuguese F", "pm": "Portuguese M",
        "zf": "Chinese F", "zm": "Chinese M",
    }
    for v in voices:
        print(f"  {v:25s} {prefixes.get(v[:2], '?')}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Speak the daily briefing")
    parser.add_argument("date", nargs="?", help="Journal date (YYYY-MM-DD)")
    parser.add_argument("--voice", default=DEFAULT_VOICE, help=f"Voice (default: {DEFAULT_VOICE})")
    parser.add_argument("--speed", type=float, default=DEFAULT_SPEED, help=f"Speed (default: {DEFAULT_SPEED})")
    parser.add_argument("--output", type=str, help="Save audio to file instead of playing")
    parser.add_argument("--telegram", action="store_true", help="Send as Telegram voice message")
    parser.add_argument("--dry-run", action="store_true", help="Print speech text only")
    parser.add_argument("--list-voices", action="store_true", help="List available voices")
    args = parser.parse_args()

    if args.list_voices:
        list_voices()
        sys.exit(0)

    journal = find_journal(args.date)
    speech_text = get_spoken_text(journal)

    if not speech_text.strip():
        print("No briefing content found.")
        sys.exit(1)

    if args.dry_run:
        print("=== Speech Text ===")
        print(speech_text)
        print(f"\n=== {len(speech_text)} chars ===")
        sys.exit(0)

    output_path = Path(args.output) if args.output else None
    audio_path, duration = generate_audio(speech_text, voice=args.voice, speed=args.speed, output_path=output_path)

    if args.telegram:
        send_telegram(audio_path)
        if not args.output:
            audio_path.unlink(missing_ok=True)
    elif not args.output:
        play_local(audio_path)
        audio_path.unlink(missing_ok=True)
    else:
        print(f"Saved: {audio_path}")
