#!/usr/bin/env python3
"""
Speak the daily briefing aloud using Kokoro TTS.

Usage:
    python speak_brief.py                     # Speak today's briefing locally
    python speak_brief.py 2026-04-18          # Specific date
    python speak_brief.py --telegram          # Send as Telegram voice message
    python speak_brief.py --output brief.wav  # Save to file
    python speak_brief.py --voice af_nova     # Different voice
    python speak_brief.py --list-voices       # Show available voices
    python speak_brief.py --dry-run           # Print speech text only

The script looks for a spoken_brief.txt next to the journal (pre-generated by
/today). If not found, it falls back to LLM summarisation of the journal.
"""

import sys
import os
import re
import argparse
import subprocess
import tempfile
from pathlib import Path
from datetime import date, timedelta

MODELS_DIR = Path(__file__).parent.parent / "models"
JOURNAL_DIR = Path.home() / "Data" / "0-personal" / "notes" / "journals"
DEFAULT_VOICE = "af_heart"
DEFAULT_SPEED = 1.0

# Crypto tickers -> full names for natural speech
CRYPTO_NAMES = {
    "SOL": "Solana", "BTC": "Bitcoin", "ETH": "Ethereum",
    "BZZ": "Swarm", "BNB": "BNB", "USDT": "Tether",
    "USDC": "USDC",
}


def find_journal(date_str=None):
    """Find journal file for given date or today/yesterday."""
    if date_str:
        p = JOURNAL_DIR / f"{date_str}.md"
        if p.exists():
            return p
        print(f"No journal found for {date_str}")
        sys.exit(1)

    today = date.today()
    for d in [today, today - timedelta(days=1)]:
        p = JOURNAL_DIR / f"{d.isoformat()}.md"
        if p.exists():
            print(f"Using journal: {d.isoformat()}")
            return p

    print("No journal found for today or yesterday.")
    sys.exit(1)


def prepare_for_tts(text):
    """Clean text for TTS: expand tickers. replace commas with dots for pacing."""
    # Expand crypto tickers (standalone word boundaries)
    for ticker, name in CRYPTO_NAMES.items():
        text = re.sub(rf'\b{ticker}\b', name, text)

    # Replace commas with dots for natural Kokoro pacing
    text = text.replace(", ", ". ")
    text = text.replace(",", ".")

    return text


def get_spoken_text(journal_path):
    """Get spoken briefing text. Prefers spoken_brief.txt if it exists."""
    # Check for pre-generated spoken brief
    spoken_file = journal_path.parent / f"{journal_path.stem}_spoken.txt"
    if spoken_file.exists():
        print(f"Using pre-generated: {spoken_file.name}")
        return prepare_for_tts(spoken_file.read_text().strip())

    # Fallback: LLM summarisation
    print("No spoken_brief.txt found. Generating via LLM...")
    return prepare_for_tts(extract_and_summarize(journal_path))


def extract_and_summarize(journal_path):
    """Extract key sections and summarize conversationally via LLM."""
    text = journal_path.read_text()
    lines = text.split("\n")

    sections = {}
    current_section = None
    current_lines = []
    for line in lines:
        if line.startswith("## "):
            if current_section:
                sections[current_section] = "\n".join(current_lines)
            current_section = line[3:].strip()
            current_lines = []
        elif current_section:
            current_lines.append(line)
    if current_section:
        sections[current_section] = "\n".join(current_lines)

    # Collect relevant sections
    targets = ["Good Morning", "Your Agenda", "Spaces", "Decisions Due", "Trading", "Data's Observation"]
    skip = ["Session:", "Token Cost"]
    relevant = []
    for target in targets:
        for name, content in sections.items():
            if name.startswith(target) or target in name:
                if any(s in name for s in skip):
                    continue
                relevant.append(f"## {name}\n{content}")
                break

    if not relevant:
        return ""

    report = "\n\n".join(relevant)
    if len(report) > 3000:
        report = report[:3000] + "\n[truncated]"

    return summarize_with_llm(report)


SUMMARIZE_PROMPT = """You are Data. A trusted butler and chief of staff. Think Jarvis from Iron Man or Alfred from Batman. Competent. Dry wit. Genuinely caring. You've read the full daily report and are delivering the morning briefing aloud while your principal has their coffee.

Rules:
- Speak naturally with personality. Warm. Slightly formal. Occasionally wry.
- DON'T read numbers dry. Translate them: "readiness 80" becomes "you're well rested". "11000 steps" becomes "you were quite active yesterday".
- DON'T list items mechanically. Weave priorities into flowing sentences.
- Keep it to 120-180 words. About 60-90 seconds of audio.
- Start with "Good morning sir." and a comment about how they're doing.
- Cover: energy/readiness. The 1-2 most important things today. Any overdue items or urgent decisions. Urgent emails that need a reply or decision (name the sender and topic). Urgent GitHub items (security issues. PRs waiting for review. Assigned issues). Meeting status. A market or trading highlight. Something stimulating from knowledge or metacognition. A stoic or mindful observation woven naturally into the briefing. A wry closing thought.
- End with something like "I've left the full report on your desk." or "The details are in your briefing whenever you're ready."
- IMPORTANT: Use dots instead of commas for pacing. Short sentences. Natural pauses.
- Use full cryptocurrency names: Solana not SOL. Bitcoin not BTC. Ethereum not ETH.
- Pure spoken text. No markdown. No bullets. No formatting. No emoji.
- British English spelling preferred.

Here is today's report:

---
{report}
---"""


def summarize_with_llm(report_text):
    """Use an LLM to create a conversational summary."""
    prompt = SUMMARIZE_PROMPT.format(report=report_text)

    # Try Anthropic API first
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if api_key:
        import anthropic
        client = anthropic.Anthropic(api_key=api_key)
        response = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=400,
            messages=[{"role": "user", "content": prompt}],
        )
        return response.content[0].text

    # Try OpenRouter
    or_key = os.environ.get("OPENROUTER_API_KEY")
    if or_key:
        import json, urllib.request
        req = urllib.request.Request(
            "https://openrouter.ai/api/v1/chat/completions",
            data=json.dumps({
                "model": "anthropic/claude-haiku-4-5-20251001",
                "max_tokens": 400,
                "messages": [{"role": "user", "content": prompt}],
            }).encode(),
            headers={"Authorization": f"Bearer {or_key}", "Content-Type": "application/json"},
        )
        with urllib.request.urlopen(req) as resp:
            data = json.loads(resp.read())
            return data["choices"][0]["message"]["content"]

    # Fallback: Ollama
    try:
        import json, urllib.request
        req = urllib.request.Request(
            "http://localhost:11434/api/generate",
            data=json.dumps({
                "model": "deepseek-r1:7b-qwen-distill-q4_K_M",
                "prompt": prompt,
                "stream": False,
            }).encode(),
            headers={"Content-Type": "application/json"},
        )
        with urllib.request.urlopen(req, timeout=60) as resp:
            data = json.loads(resp.read())
            return data["response"]
    except Exception as e:
        print(f"All LLM backends failed. Set ANTHROPIC_API_KEY or OPENROUTER_API_KEY or run ollama.")
        print(f"Last error: {e}")
        sys.exit(1)


def _generate_audio_kokoro(text, voice=DEFAULT_VOICE, speed=DEFAULT_SPEED, output_path=None):
    """Generate speech with Kokoro ONNX. Returns (path, duration)."""
    from kokoro_onnx import Kokoro
    import soundfile as sf
    import numpy as np

    model_path = MODELS_DIR / "kokoro-v1.0.onnx"
    voices_path = MODELS_DIR / "voices-v1.0.bin"

    if not model_path.exists():
        raise FileNotFoundError(f"Kokoro model not found at {model_path}")

    print(f"Loading Kokoro ({voice})...")
    kokoro = Kokoro(str(model_path), str(voices_path))

    paragraphs = [p.strip() for p in re.split(r'\n\n+', text) if p.strip()]

    all_samples = []
    sr = None
    chunk_count = 0

    for pi, paragraph in enumerate(paragraphs):
        sentences = re.split(r'(?<=[.!?])\s+', paragraph)
        chunks = []
        current = ""
        for s in sentences:
            if len(current) + len(s) > 400:
                if current:
                    chunks.append(current.strip())
                current = s
            else:
                current = current + " " + s if current else s
        if current:
            chunks.append(current.strip())

        for chunk in chunks:
            samples, sr = kokoro.create(chunk, voice=voice, speed=speed)
            all_samples.append(samples)
            all_samples.append(np.zeros(int(sr * 0.3)))
            chunk_count += 1

        if pi < len(paragraphs) - 1 and sr:
            all_samples.append(np.zeros(int(sr * 1.0)))

    print(f"Generating {chunk_count} audio chunks across {len(paragraphs)} sections...")

    combined = np.concatenate(all_samples)
    duration = len(combined) / sr

    if output_path is None:
        f = tempfile.NamedTemporaryFile(suffix=".wav", delete=False)
        output_path = f.name
        f.close()

    sf.write(str(output_path), combined, sr)
    print(f"Audio: {duration:.0f}s -> {output_path}")
    return Path(output_path), duration


def _generate_audio_gtts(text, output_path=None):
    """Fallback TTS via gTTS (Google). No local models needed. Returns (path, duration)."""
    from gtts import gTTS

    if output_path is None:
        f = tempfile.NamedTemporaryFile(suffix=".mp3", delete=False)
        output_path = f.name
        f.close()

    print("Using gTTS fallback (Google TTS, no local models required)...")
    tts = gTTS(text=text, lang="en", slow=False)
    tts.save(str(output_path))

    # Rough duration estimate: ~150 words/minute
    duration = len(text.split()) / 150 * 60
    print(f"gTTS audio saved ({duration:.0f}s estimated) -> {output_path}")
    return Path(output_path), duration


def generate_audio(text, voice=DEFAULT_VOICE, speed=DEFAULT_SPEED, output_path=None):
    """Generate speech. Tries Kokoro first, falls back to gTTS. Returns (path, duration)."""
    try:
        return _generate_audio_kokoro(text, voice=voice, speed=speed, output_path=output_path)
    except FileNotFoundError as e:
        print(f"Kokoro unavailable ({e}) — trying gTTS")
    except ImportError:
        print("kokoro_onnx not installed — trying gTTS")
    except Exception as e:
        print(f"Kokoro error ({e}) — trying gTTS")

    return _generate_audio_gtts(text, output_path=output_path)


def convert_to_ogg(audio_path):
    """Convert audio (WAV or MP3) to OGG/Opus for Telegram voice messages.

    Returns the OGG path, or None if ffmpeg is unavailable.
    """
    ogg_path = audio_path.with_suffix(".ogg")
    try:
        result = subprocess.run(
            ["ffmpeg", "-y", "-i", str(audio_path), "-c:a", "libopus", "-b:a", "48k", str(ogg_path)],
            capture_output=True,
        )
        if result.returncode == 0:
            return ogg_path
        print(f"ffmpeg conversion failed (exit {result.returncode}): {result.stderr[-200:]}")
        return None
    except FileNotFoundError:
        print("ffmpeg not found — will send as audio (not voice) instead")
        return None


def _load_telegram_creds(env_file=None):
    """Return (bot_token, chat_id) from env or env files."""
    env_path = env_file or (
        Path.home() / "Data" / ".datacore" / "env" / "mrdata.env"
        if (Path.home() / "Data" / ".datacore" / "env" / "mrdata.env").exists()
        else Path.home() / "Data" / ".datacore" / "env" / "gateio.env"
    )
    env = {}
    if Path(env_path).exists():
        for line in Path(env_path).read_text().strip().split("\n"):
            if "=" in line and not line.startswith("#"):
                k, v = line.split("=", 1)
                env[k.strip()] = v.strip()
    # Also check nightshift.env (server config)
    ns_env = Path.home() / "config" / "nightshift.env"
    if ns_env.exists():
        for line in ns_env.read_text().strip().split("\n"):
            if "=" in line and not line.startswith("#"):
                k, v = line.split("=", 1)
                env.setdefault(k.strip(), v.strip())

    bot_token = os.environ.get("TELEGRAM_BOT_TOKEN") or env.get("TELEGRAM_BOT_TOKEN")
    chat_id = os.environ.get("TELEGRAM_CHAT_ID") or env.get("TELEGRAM_CHAT_ID")
    return bot_token, chat_id


def _telegram_send_file(bot_token, chat_id, audio_path, api_method, field_name, content_type, filename):
    """Low-level multipart upload to Telegram Bot API."""
    import json, urllib.request
    url = f"https://api.telegram.org/bot{bot_token}/{api_method}"
    boundary = "----FormBoundary"
    audio_data = Path(audio_path).read_bytes()
    body = (
        f"--{boundary}\r\n"
        f'Content-Disposition: form-data; name="chat_id"\r\n\r\n{chat_id}\r\n'
        f"--{boundary}\r\n"
        f'Content-Disposition: form-data; name="{field_name}"; filename="{filename}"\r\n'
        f"Content-Type: {content_type}\r\n\r\n"
    ).encode() + audio_data + f"\r\n--{boundary}--\r\n".encode()
    req = urllib.request.Request(
        url, data=body,
        headers={"Content-Type": f"multipart/form-data; boundary={boundary}"},
    )
    with urllib.request.urlopen(req) as resp:
        return json.loads(resp.read())


def send_telegram(audio_path, env_file=None):
    """Send audio as Telegram voice message.

    Tier 1: sendVoice (OGG/Opus — requires ffmpeg)
    Tier 2: sendAudio (MP3/WAV — no ffmpeg needed)
    """
    bot_token, chat_id = _load_telegram_creds(env_file)
    if not bot_token or not chat_id:
        print("Missing TELEGRAM_BOT_TOKEN or TELEGRAM_CHAT_ID")
        sys.exit(1)

    audio_path = Path(audio_path)

    # Tier 1: convert to OGG and send as voice message
    ogg_path = convert_to_ogg(audio_path)
    if ogg_path and ogg_path.exists():
        try:
            result = _telegram_send_file(
                bot_token, chat_id, ogg_path,
                "sendVoice", "voice", "audio/ogg", "briefing.ogg",
            )
            ogg_path.unlink(missing_ok=True)
            if result.get("ok"):
                print("Sent to Telegram as voice message!")
                return
            print(f"sendVoice failed: {result} — falling back to sendAudio")
        except Exception as e:
            print(f"sendVoice error: {e} — falling back to sendAudio")
        finally:
            ogg_path.unlink(missing_ok=True)

    # Tier 2: send original file as audio (MP3 or WAV — Telegram accepts both)
    suffix = audio_path.suffix.lower()
    content_type = "audio/mpeg" if suffix == ".mp3" else "audio/wav"
    filename = f"briefing{suffix}"
    try:
        result = _telegram_send_file(
            bot_token, chat_id, audio_path,
            "sendAudio", "audio", content_type, filename,
        )
        if result.get("ok"):
            print(f"Sent to Telegram as audio file ({suffix})!")
        else:
            print(f"sendAudio also failed: {result}")
    except Exception as e:
        print(f"sendAudio error: {e}")


def play_local(audio_path):
    """Play audio locally via afplay (macOS)."""
    subprocess.run(["afplay", str(audio_path)], check=False)


def list_voices():
    from kokoro_onnx import Kokoro
    kokoro = Kokoro(str(MODELS_DIR / "kokoro-v1.0.onnx"), str(MODELS_DIR / "voices-v1.0.bin"))
    voices = sorted(kokoro.get_voices())
    print("Available voices:")
    prefixes = {
        "af": "American F", "am": "American M", "bf": "British F", "bm": "British M",
        "ef": "Spanish F", "em": "Spanish M", "ff": "French F", "hf": "Hindi F",
        "hm": "Hindi M", "if": "Italian F", "im": "Italian M", "jf": "Japanese F",
        "jm": "Japanese M", "pf": "Portuguese F", "pm": "Portuguese M",
        "zf": "Chinese F", "zm": "Chinese M",
    }
    for v in voices:
        print(f"  {v:25s} {prefixes.get(v[:2], '?')}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Speak the daily briefing")
    parser.add_argument("date", nargs="?", help="Journal date (YYYY-MM-DD)")
    parser.add_argument("--voice", default=DEFAULT_VOICE, help=f"Voice (default: {DEFAULT_VOICE})")
    parser.add_argument("--speed", type=float, default=DEFAULT_SPEED, help=f"Speed (default: {DEFAULT_SPEED})")
    parser.add_argument("--output", type=str, help="Save audio to file instead of playing")
    parser.add_argument("--telegram", action="store_true", help="Send as Telegram voice message")
    parser.add_argument("--dry-run", action="store_true", help="Print speech text only")
    parser.add_argument("--list-voices", action="store_true", help="List available voices")
    args = parser.parse_args()

    if args.list_voices:
        list_voices()
        sys.exit(0)

    journal = find_journal(args.date)
    speech_text = get_spoken_text(journal)

    if not speech_text.strip():
        print("No briefing content found.")
        sys.exit(1)

    if args.dry_run:
        print("=== Speech Text ===")
        print(speech_text)
        print(f"\n=== {len(speech_text)} chars ===")
        sys.exit(0)

    output_path = Path(args.output) if args.output else None
    audio_path, duration = generate_audio(speech_text, voice=args.voice, speed=args.speed, output_path=output_path)

    if args.telegram:
        send_telegram(audio_path)
        if not args.output:
            audio_path.unlink(missing_ok=True)
    elif not args.output:
        play_local(audio_path)
        audio_path.unlink(missing_ok=True)
    else:
        print(f"Saved: {audio_path}")
