"""A configured-but-broken backend must not take down the fallback chain.

From 2026-08-06 the nightshift box had ANTHROPIC_API_KEY set to a key with no
credit ("Your credit balance is too low to access the Anthropic API"). In the
old summarize_with_llm only the last branch (ollama) sat inside a try/except,
so the dead primary raised and OpenRouter and ollama were never reached — a
chain whose entire purpose is surviving one backend being down was defeated by
one backend being down.

The box also had no entry for `claude -p`, which was its ONLY working backend.
"""

import importlib.util
import sys
import types
from pathlib import Path

import pytest

LIB = Path(__file__).resolve().parent.parent / "lib" / "speak_brief.py"


@pytest.fixture()
def sb(monkeypatch):
    # speak_brief imports heavy TTS deps at module scope; stub what is missing.
    for name in ("kokoro_onnx", "soundfile", "numpy"):
        if name not in sys.modules:
            monkeypatch.setitem(sys.modules, name, types.ModuleType(name))
    spec = importlib.util.spec_from_file_location("speak_brief_t", LIB)
    mod = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(mod)
    except Exception as e:  # pragma: no cover - environment-dependent
        pytest.skip(f"speak_brief not importable here: {e}")
    return mod


def _chain(sb, monkeypatch, backends):
    monkeypatch.setattr(sb, "LLM_BACKENDS", tuple(backends))


def test_broken_primary_falls_through_to_next(sb, monkeypatch, capsys):
    def dead(_):
        raise RuntimeError("Your credit balance is too low")

    _chain(sb, monkeypatch, [("anthropic-api", dead), ("claude-cli", lambda _: "spoken text")])
    assert sb.summarize_with_llm("report") == "spoken text"
    out = capsys.readouterr().out
    assert "credit balance is too low" in out.lower()
    assert "generated by 'claude-cli'" in out


def test_unconfigured_backend_is_skipped_not_fatal(sb, monkeypatch):
    _chain(sb, monkeypatch, [("anthropic-api", lambda _: None), ("ollama", lambda _: "local text")])
    assert sb.summarize_with_llm("report") == "local text"


def test_empty_output_falls_through(sb, monkeypatch):
    _chain(sb, monkeypatch, [("a", lambda _: "   "), ("b", lambda _: "real")])
    assert sb.summarize_with_llm("report") == "real"


def test_all_failing_exits_with_every_reason(sb, monkeypatch, capsys):
    def dead(_):
        raise RuntimeError("no credit")

    _chain(sb, monkeypatch, [("anthropic-api", dead), ("ollama", lambda _: None)])
    with pytest.raises(SystemExit) as exc:
        sb.summarize_with_llm("report")
    assert exc.value.code == 1
    out = capsys.readouterr().out
    assert "anthropic-api" in out and "ollama" in out
    assert "unset ANTHROPIC_API_KEY" in out


class _CompletedProcess:
    def __init__(self, returncode=0, stdout="ok", stderr=""):
        self.returncode = returncode
        self.stdout = stdout
        self.stderr = stderr


def test_claude_cli_strips_the_api_key_from_its_env(sb, monkeypatch):
    """A set ANTHROPIC_API_KEY overrides the claude.ai login — never pass it on.

    This is the exact defect that produced five mornings of fallback briefings:
    the systemd unit loaded an env file containing a credit-less key, and
    `claude -p` routed to the metered API instead of the Max subscription.
    """
    monkeypatch.setenv("ANTHROPIC_API_KEY", "sk-dead")
    captured = {}

    def fake_run(*args, **kwargs):
        captured["env"] = kwargs.get("env", {})
        return _CompletedProcess()

    monkeypatch.setattr(sb.subprocess, "run", fake_run)
    assert sb._try_claude_cli("prompt") == "ok"
    assert "ANTHROPIC_API_KEY" not in captured["env"]
    assert captured["env"], "the rest of the environment must still be passed through"


def test_claude_cli_raises_with_detail_on_nonzero_exit(sb, monkeypatch):
    monkeypatch.delenv("ANTHROPIC_API_KEY", raising=False)
    monkeypatch.setattr(
        sb.subprocess, "run",
        lambda *a, **k: _CompletedProcess(returncode=1, stdout="", stderr="Not logged in"),
    )
    with pytest.raises(RuntimeError, match="Not logged in"):
        sb._try_claude_cli("prompt")
