#!/usr/bin/env python3
"""Convert the markdown Intent Graph into org form, once.

Why
---
`2-datacore/1-tracks/ops/Intent-Graph.md` holds the real structure — five
levels, adapted from the Swarm Foundation Mission.md intent graph: Vision ->
Intents -> Strategic goals (with success criteria) -> Initiatives -> Projects.
Multi-parent nodes are marked inline as `[*3: Intent 1, 4, 5]` and the doc
declares them high-leverage: "multi-intent projects get worked on first."

`modules/gtd/skills/intent-routing.md` kept only the five level-1 rows, as a
flat keyword table, and that projection is what every scorer has read since.
The 19 measurable goals and their success criteria were dropped.

Org form fixes this without a new parser: org-workspace already gives nesting,
properties and tags, so heading depth carries "what serves what" and a
:SERVES: property carries the cross-branch edges that make it a DAG. The
markdown stays as the human-readable narrative; the org file is what code
reads.

    python3 intent_graph_convert.py --out .datacore/intents.org
    python3 intent_graph_convert.py --dry-run
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from tag_utils import to_org_tag  # noqa: E402  (org tags: [A-Za-z0-9_@#%] only)

SRC = "2-datacore/1-tracks/ops/Intent-Graph.md"

#: `[*3: Intent 1, 4, 5]` — the doc's inline notation for multi-parent nodes.
MULTI = re.compile(r"`\[\*(\d+):\s*Intent\s*([\d,\s]+)\]`")
#: "- **Node title** ..." is a level-2 strategic goal.
L2 = re.compile(r"^- \*\*(.+?)\*\*(.*)$")
#: "    - Success: ..." carries the measurable criterion; siblings are L3.
CHILD = re.compile(r"^\s{2,}- (.+)$")
SUCCESS = re.compile(r"^Success:\s*(.+)$", re.I)


def slug(text: str, taken: set[str]) -> str:
    """Stable, readable id. Ids are what :SERVES: and task :INTENT: point at,
    so they must not churn when the prose is edited — derived from the first
    few significant words rather than a hash of the whole line."""
    words = re.findall(r"[a-z0-9]+", text.lower())
    stop = {"the", "a", "an", "is", "are", "as", "of", "for", "to", "and",
            "in", "on", "with", "without", "that", "by"}
    keep = [w for w in words if w not in stop][:4] or words[:4] or ["node"]
    base = "-".join(keep)
    out, n = base, 2
    while out in taken:
        out, n = f"{base}-{n}", n + 1
    taken.add(out)
    return out


def parse(md: str) -> dict:
    """Extract vision, the five intents, and their level-2 goals."""
    vision = ""
    m = re.search(r"^## Vision\s*\n+\*\*(.+?)\*\*", md, re.M)
    if m:
        vision = m.group(1).strip()

    intents, cur = [], None
    body = md.split("## Intents", 1)[-1].split("## Multi-Intent", 1)[0]
    for line in body.splitlines():
        h = re.match(r"^### \d+\.\s*(.+)$", line)
        if h:
            cur = {"title": h.group(1).strip(), "note": "", "goals": []}
            intents.append(cur)
            continue
        if cur is None:
            continue
        g = L2.match(line)
        if g:
            title, tail = g.group(1).strip(), g.group(2)
            mm = MULTI.search(tail)
            cur["goals"].append({
                "title": title,
                "serves": [int(x) for x in re.findall(r"\d+", mm.group(2))] if mm else [],
                "dip": (re.search(r"\((DIP-\d+[^)]*)\)", tail).group(1)
                        if re.search(r"\((DIP-\d+[^)]*)\)", tail) else ""),
                "experiment": "(EXPERIMENT)" in tail,
                "success": "", "children": [],
            })
            continue
        c = CHILD.match(line)
        if c and cur["goals"]:
            text = c.group(1).strip()
            s = SUCCESS.match(text)
            if s:
                cur["goals"][-1]["success"] = s.group(1).strip()
            else:
                cur["goals"][-1]["children"].append(text)
            continue
        if line.strip() and not line.startswith(("|", "-", "#", "```")) and not cur["note"]:
            cur["note"] = line.strip()
    return {"vision": vision, "intents": intents}


def render(g: dict) -> str:
    """Heading depth IS the level. A child heading obviously serves its
    parent, so no property is needed for the tree — only for cross-links."""
    taken: set[str] = set()
    out = [
        "#+TITLE: Intent Graph",
        "#+CATEGORY: intent",
        "#+STARTUP: overview",
        "",
        "# Generated by .datacore/lib/intent_graph_convert.py from",
        "# 2-datacore/1-tracks/ops/Intent-Graph.md — the narrative stays there,",
        "# this is the machine-readable form. Heading depth = graph level:",
        "#   *     vision      why any of it matters",
        "#   **    intent      aspirational, five max",
        "#   ***   goal        measurable, carries :SUCCESS:",
        "#   ****  initiative  multi-month effort",
        "#   ***** project     bounded and deliverable — the leaves",
        "#",
        "# Nesting carries what-serves-what. :SERVES: carries the extra parents",
        "# that make this a DAG: per the source doc, multi-intent nodes are",
        "# high-leverage and get worked on first.",
        "",
    ]
    vid = slug(g["vision"] or "vision", taken)
    out.append(f"* {g['vision']}  :vision:")
    out += ["  :PROPERTIES:", f"  :INTENT_ID: {vid}", "  :END:", ""]

    intent_ids: dict[int, str] = {}
    for i, it in enumerate(g["intents"], 1):
        intent_ids[i] = slug(it["title"], taken)

    for i, it in enumerate(g["intents"], 1):
        out.append(f"** {it['title']}  :intent:")
        out += ["   :PROPERTIES:", f"   :INTENT_ID: {intent_ids[i]}",
                f"   :LEVEL: 1", "   :END:"]
        if it["note"]:
            out += ["", f"   {it['note']}"]
        out.append("")
        for goal in it["goals"]:
            tags = [to_org_tag("goal")]
            if goal["serves"]:
                tags.append(to_org_tag("high_leverage"))
            if goal["experiment"]:
                tags.append(to_org_tag("experiment"))
            gid = slug(goal["title"], taken)
            out.append(f"*** {goal['title']}  :{':'.join(tags)}:")
            props = ["    :PROPERTIES:", f"    :INTENT_ID: {gid}", "    :LEVEL: 2"]
            if goal["success"]:
                props.append(f"    :SUCCESS: {goal['success']}")
            # Cross-links to the OTHER intents this serves. The tree parent is
            # implicit; these are the additional edges.
            extra = [intent_ids[n] for n in goal["serves"]
                     if n in intent_ids and intent_ids[n] != intent_ids[i]]
            if extra:
                props.append(f"    :SERVES: {' '.join(extra)}")
            if goal["dip"]:
                props.append(f"    :DIP: {goal['dip']}")
            props.append("    :END:")
            out += props + [""]
            for ch in goal["children"]:
                out.append(f"**** {ch}  :initiative:")
                out += ["     :PROPERTIES:", f"     :INTENT_ID: {slug(ch, taken)}",
                        "     :LEVEL: 3", "     :END:"]
            if goal["children"]:
                out.append("")
    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=str(Path.home() / "Data"))
    ap.add_argument("--out", default=".datacore/intents.org")
    ap.add_argument("--dry-run", action="store_true")
    a = ap.parse_args()
    root = Path(a.root).expanduser()
    src = root / SRC
    if not src.is_file():
        print(f"source not found: {src}", file=sys.stderr)
        return 1
    g = parse(src.read_text())
    text = render(g)
    n_goals = sum(len(i["goals"]) for i in g["intents"])
    n_succ = sum(1 for i in g["intents"] for x in i["goals"] if x["success"])
    n_multi = sum(1 for i in g["intents"] for x in i["goals"] if x["serves"])
    n_init = sum(len(x["children"]) for i in g["intents"] for x in i["goals"])
    print(f"  vision: {'yes' if g['vision'] else 'MISSING'}")
    print(f"  intents: {len(g['intents'])}  goals: {n_goals} "
          f"({n_succ} with success criteria, {n_multi} high-leverage)")
    print(f"  initiatives: {n_init}")
    if a.dry_run:
        print("\n" + "\n".join(text.splitlines()[:40]))
        return 0
    dest = root / a.out
    dest.write_text(text)
    print(f"  wrote {dest} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
