#!/usr/bin/env python3
"""
Nightshift inbox classifier: scan, report, archive, index.

Discovers all nightshift-related files in 0-personal/0-inbox/ using three-pass
detection, normalizes metadata across formats, classifies files, scores knowledge
candidates, and supports archiving with manifest/index generation.

Run from ~/Data directory.

Subcommands:
    scan     - Discover and classify all nightshift files, output JSON
    report   - Generate human-readable report from latest scan
    archive  - Move files to archive (--execute to actually move, dry-run default)
    index    - Generate _manifest.yaml per month + _index.md in archive
"""

import hashlib
import json
import os
import re
import shutil
import sys
import yaml
from collections import Counter, defaultdict
from dataclasses import dataclass, field, asdict
from datetime import datetime
from pathlib import Path

# Vendor the two small functions from nightshift_inbox_cleanup to avoid
# fragile sys.path import coupling (CTO issue #2).

DATA_DIR = Path(os.environ.get("DATA_DIR", Path.home() / "Data"))
INBOX = DATA_DIR / "0-personal" / "0-inbox"
ARCHIVE_BASE = DATA_DIR / "0-personal" / "4-archive" / "nightshift"
STATE_DIR = DATA_DIR / ".datacore" / "state"


def archive_path(space: str, filename: str, created: str) -> Path:
    """Get archive destination for a file (vendored from nightshift_inbox_cleanup)."""
    month = None
    if created:
        m = re.search(r'(\d{4}-\d{2})', created)
        if m:
            month = m.group(1)
    if not month:
        m = re.search(r'(\d{4}-\d{2}-\d{2})', filename)
        if m:
            month = m.group(1)[:7]
    if not month:
        month = "unknown"
    return DATA_DIR / space / "4-archive" / "nightshift" / month / filename


def normalize_title(title: str) -> str:
    """Normalize title for dedup grouping (vendored from nightshift_inbox_cleanup)."""
    t = title.lower().strip()
    t = re.sub(r'\[#[a-c]\]\s*', '', t)
    t = t.strip(" -:.")
    return t


# --- Detection markers ---

FRONTMATTER_MARKERS = [
    "nightshift_id:", "task-source: nightshift",
    "source-task: nightshift", "type: nightshift-output",
]
HEADER_MARKERS = [
    "Generated by nightshift", "Nightshift execution",
]
# Bold-header markers for Pass 3 (Data issue #2: detect bold-header format)
BOLD_HEADER_MARKERS = [
    re.compile(r'\*\*Task.*?nightshift', re.IGNORECASE),
    re.compile(r'\*\*Source.*?nightshift', re.IGNORECASE),
    re.compile(r'\*\*Task ID:\*\*\s*nightshift', re.IGNORECASE),
]

# --- Domain signals ---
# Each pattern is (regex, is_high_specificity). High-specificity terms alone
# suffice for domain assignment (threshold=1). General terms require 2+ matches.

DOMAIN_SIGNALS = {
    "datafund": [
        (r"\bdatafund\b", True), (r"\bfair data\b", False), (r"\bdata economy\b", False),
        (r"\bfdp\b", False), (r"\bfairdrop\b", True), (r"\brwa\b", False),
        (r"\bswarm\b", False), (r"\bfds\b", False), (r"\bsovereign\b", False),
    ],
    "datacore": [
        (r"\bdatacore\b", True), (r"\bdip-\d+", False), (r"\bengram\b", True),
        (r"\bnightshift module\b", False), (r"\bzettel\b", False),
        (r"\bmodule\.yaml\b", False), (r"\bCLAUDE\.md\b", False),
    ],
    "trading": [
        (r"\btrading\b", False), (r"\bwyckoff\b", True), (r"\bposition health\b", False),
        (r"\bliquidation\b", False), (r"\bredalert\b", False), (r"\bIMR\b", False),
    ],
}


@dataclass
class FileRecord:
    path: str               # relative to DATA_DIR
    filename: str
    detection: str          # prefix | subdir | body_marker
    title: str = ""
    created: str = ""       # YYYY-MM-DD
    score: float = None
    status: str = "unknown" # approved | needs_review | failed | unknown
    task_type: str = ""     # :AI:research: etc.
    file_type: str = ""     # exec_report | deliverable | failure | summary | status_note
    domain: str = "personal"
    word_count: int = 0
    structure_score: float = 0.0  # gradient 0.0-1.0 (was binary has_structure)
    linked_files: list = field(default_factory=list)
    category: str = ""      # archive | knowledge | failed | review | duplicate
    knowledge_score: float = 0.0
    content_hash: str = ""  # first 2000 chars hash for dedup content comparison
    keywords: list = field(default_factory=list)  # extracted from headings/bold terms


# ---- Discovery (three-pass) ----

def discover_files() -> tuple[list[dict], list[str]]:
    """Find all nightshift-related files using three passes.
    Returns (files, read_warnings)."""
    files = []
    seen = set()
    read_warnings = []

    # Pass 1: Filename prefix
    for pattern in ["nightshift-*.md", "FAILED-nightshift-*.md"]:
        for f in sorted(INBOX.glob(pattern)):
            files.append({"path": f, "detection": "prefix"})
            seen.add(f)

    # Pass 2: Subdirectory logs
    logs_dir = INBOX / "ingest" / "nightshift-logs"
    if logs_dir.exists():
        for f in sorted(logs_dir.glob("nightshift-*.md")):
            if f not in seen:
                files.append({"path": f, "detection": "subdir"})
                seen.add(f)

    # Pass 3: Body-text scan for non-prefixed deliverables
    for f in sorted(INBOX.glob("*.md")):
        if f in seen:
            continue
        try:
            header = f.read_text(errors="replace")[:1000]
            if any(marker in header for marker in FRONTMATTER_MARKERS + HEADER_MARKERS):
                files.append({"path": f, "detection": "body_marker"})
                seen.add(f)
                continue
            if any(pat.search(header) for pat in BOLD_HEADER_MARKERS):
                files.append({"path": f, "detection": "body_marker"})
                seen.add(f)
                continue
            if re.search(r'nightshift-L\d+', header[:500]):
                files.append({"path": f, "detection": "body_marker_weak"})
                seen.add(f)
        except Exception as e:
            read_warnings.append(f"Pass 3 read error: {f.name}: {e}")

    return files, read_warnings


# ---- Metadata parsing ----

def parse_yaml_frontmatter(text: str) -> dict:
    """Parse ---\\nkey: value\\n--- format."""
    meta = {}
    if not text.startswith("---"):
        return meta
    end = text.find("---", 3)
    if end < 0:
        return meta
    fm = text[3:end]
    for line in fm.split("\n"):
        line = line.strip()
        if line.startswith("title:"):
            meta["title"] = line[6:].strip().strip('"').strip("'")
        elif line.startswith("score:"):
            try:
                meta["score"] = float(line[6:].strip())
            except ValueError:
                pass
        elif line.startswith("status:"):
            meta["status"] = line[7:].strip().lower()
        elif line.startswith("created:"):
            val = line[8:].strip().strip('"').strip("'")
            meta["created"] = val[:10]
        elif line.startswith("task_type:") or line.startswith("task-type:"):
            meta["task_type"] = line[10:].strip().strip('"')
        elif line.startswith("nightshift_id:"):
            meta["nightshift_id"] = line[14:].strip()
        elif line.startswith("task-source:"):
            meta["task_source"] = line[12:].strip()
    return meta


def parse_bold_header(text: str) -> dict:
    """Parse **Key:** Value format found in research/analysis outputs."""
    meta = {}
    for m in re.finditer(r'\*\*(\w[\w\s]*?):\*\*\s*(.+)', text[:1500]):
        key = m.group(1).strip().lower().replace(' ', '_')
        val = m.group(2).strip()
        if key in ('created', 'date', 'research_date', 'generated'):
            meta['created'] = val[:10]
        elif key == 'score':
            try:
                meta['score'] = float(val)
            except ValueError:
                pass
        elif key == 'status':
            meta['status'] = val.lower()
        elif key in ('type', 'task_type'):
            meta['task_type'] = val
        elif key in ('purpose', 'topic', 'research_topic'):
            if 'title' not in meta:
                meta['title'] = val
        elif key == 'task':
            if 'title' not in meta:
                meta['title'] = val
        elif key == 'task_id':
            meta['task_source'] = val
    return meta


def parse_heading_only(text: str) -> dict:
    """Fallback: extract title from first # heading."""
    for line in text.split("\n")[:20]:
        if line.startswith("# "):
            return {"title": line[2:].strip()}
    return {}


def parse_metadata_from_text(text: str, path: Path) -> dict:
    """Unified parser: YAML > bold-header > heading > filename.
    Takes pre-read text to avoid double I/O (CTO issue #1)."""
    meta = {}
    if text.startswith("---"):
        meta = parse_yaml_frontmatter(text)

    bold = parse_bold_header(text)
    for k, v in bold.items():
        if k not in meta or meta[k] is None:
            meta[k] = v

    if not meta.get("title"):
        meta.update(parse_heading_only(text))
    if not meta.get("title"):
        meta["title"] = path.stem.replace("-", " ").replace("_", " ")

    if not meta.get("created"):
        m = re.search(r'(\d{4}-\d{2}-\d{2})', path.name)
        if m:
            meta["created"] = m.group(1)

    # Fallback to file mtime for files with no date signal
    if not meta.get("created") and path.exists():
        try:
            mtime = datetime.fromtimestamp(path.stat().st_mtime)
            meta["created"] = mtime.strftime("%Y-%m-%d")
        except Exception:
            pass

    return meta


# ---- Classification ----

def compute_structure_score(text: str) -> float:
    """Gradient structure score 0.0-1.0 (was binary has_structure).
    Counts structural elements and normalizes. (Data issue #1)"""
    heading_count = text.count("\n## ")
    table_count = len(re.findall(r'\|.*\|.*\n\|[-:| ]+\|', text))
    code_count = text.count("```") // 2  # pairs
    bold_header_count = len(re.findall(r'\*\*\w[\w\s]*?:\*\*', text[:3000]))

    # Each element contributes; cap at 1.0
    # headings: up to 0.4 (10+ headings = max), tables: up to 0.3, code: up to 0.2, bold: up to 0.1
    h = min(heading_count / 10.0, 1.0) * 0.4
    t = min(table_count / 3.0, 1.0) * 0.3
    c = min(code_count / 3.0, 1.0) * 0.2
    b = min(bold_header_count / 5.0, 1.0) * 0.1
    return round(h + t + c + b, 3)


def classify_file_type(filename: str, meta: dict, text: str) -> str:
    """Classify by content structure. Takes pre-read text (CTO issue #1)."""
    if "nightshift-exec-" in filename:
        return "exec_report"
    if "failure-report" in filename or filename.startswith("FAILED-"):
        return "failure"
    if meta.get("status") in ("failed",):
        return "failure"
    if "nightshift-summary" in filename or "nightshift-report" in filename:
        return "summary"

    word_count = len(text.split())
    struct = compute_structure_score(text)

    if word_count > 500 and struct >= 0.1:
        return "deliverable"
    if word_count < 200:
        return "status_note"
    return "deliverable"


def detect_domain(title: str, text_head: str) -> str:
    """Detect domain using tagged pattern tuples (pattern, is_high_specificity)."""
    combined = (title + " " + text_head[:1000]).lower()
    scores = {}
    has_high_spec = {}
    for domain, patterns in DOMAIN_SIGNALS.items():
        match_count = 0
        found_high_spec = False
        for pattern, is_high in patterns:
            if re.search(pattern, combined):
                match_count += 1
                if is_high:
                    found_high_spec = True
        scores[domain] = match_count
        has_high_spec[domain] = found_high_spec

    best = max(scores, key=scores.get)
    if has_high_spec.get(best) and scores[best] >= 1:
        return best
    if scores[best] >= 2:
        return best
    return "personal"


def extract_keywords(text: str, max_keywords: int = 8) -> list[str]:
    """Extract keywords from headings and bold terms for manifest searchability."""
    keywords = set()
    for m in re.finditer(r'^#{1,3}\s+(.+)$', text, re.MULTILINE):
        # Split heading into words, filter short/common ones
        for word in re.findall(r'[A-Za-z]{4,}', m.group(1)):
            keywords.add(word.lower())
    for m in re.finditer(r'\*\*([A-Za-z][\w\s]{3,30}?)\*\*', text[:3000]):
        for word in re.findall(r'[A-Za-z]{4,}', m.group(1)):
            keywords.add(word.lower())
    # Remove common/generic words
    stop = {"this", "that", "with", "from", "have", "been", "will", "would",
            "could", "should", "which", "their", "about", "into", "more",
            "than", "each", "also", "when", "what", "your", "they", "some",
            "implementation", "report", "task", "file", "output", "created",
            "using", "based", "after", "before", "between", "through",
            "action", "actions", "actual", "actually", "already", "always",
            "application", "automatically", "best", "cases", "code", "command",
            "config", "current", "data", "default", "ensure", "error",
            "example", "existing", "following", "function", "here", "just",
            "like", "make", "need", "note", "only", "other", "over", "part",
            "result", "running", "same", "section", "step", "still", "such",
            "sure", "system", "then", "there", "these", "time", "used",
            "user", "value", "work", "working", "complete", "done"}
    keywords -= stop
    return sorted(keywords)[:max_keywords]


def find_linked_outputs(text: str) -> list[str]:
    """Parse references to output files from exec reports."""
    links = []
    for m in re.finditer(r'(?:Output|Created|Generated|Wrote).*?:\s*`?([^\s`]+\.md)`?', text):
        links.append(m.group(1))
    for m in re.finditer(r'nightshift-L(\d+)', text):
        links.append(f"nightshift-L{m.group(1)}")
    for m in re.finditer(r'task-source:\s*nightshift-L(\d+)', text):
        links.append(f"nightshift-L{m.group(1)}")
    return list(set(links))


def compute_knowledge_score(record: FileRecord) -> float:
    """Composite score: higher = more likely to contain extractable knowledge.

    Weights: word_count 0.25, structure 0.25, nightshift_score 0.30, domain 0.20.
    Threshold: 0.65 flags for human review (not auto-extraction).

    Calibration examples (from 2026-03-13 scan):
      0.850  4348w struct=0.76 trading   -> knowledge (market intelligence spec)
      0.750  3112w struct=0.60 personal  -> knowledge (email closing playbook)
      0.650   881w struct=0.76 datafund  -> knowledge (borderline: reference deck analysis)
      0.647   973w struct=0.70 datacore  -> archive (just below: oauth refresh guidance)
      0.500   350w struct=0.20 personal  -> archive (short status note)

    Weight sensitivity (what breaks if you change it):
      word_count >0.30: verbose exec reports (~800w) cross 0.65, flooding knowledge
      structure  >0.30: well-formatted status notes (struct=0.8, 200w) become candidates
      ns_score   <0.25: unscored deliverables (score=None -> 0.15 default) drop too low
      domain     >0.25: domain alone flips 50+ borderline files across threshold
    """
    score = 0.0
    wc_norm = min(record.word_count / 2000.0, 1.0)
    score += wc_norm * 0.25
    # Gradient structure score (was binary 0/0.25)
    score += record.structure_score * 0.25
    if record.score is not None:
        score += record.score * 0.30
    else:
        score += 0.15
    if record.domain != "personal":
        score += 0.20
    else:
        score += 0.10
    return round(score, 3)


def route_file(record: FileRecord) -> str:
    """Determine routing category."""
    if record.file_type == "failure":
        return "failed"
    if record.file_type in ("exec_report", "status_note", "summary"):
        return "archive"
    if record.file_type == "deliverable":
        if record.knowledge_score >= 0.65:
            return "knowledge"
        # Weak-detection files without nightshift score need human verification
        if record.detection in ("body_marker", "body_marker_weak") and record.score is None:
            return "review"
        # Short prefix/subdir deliverables without quality signal — ambiguous
        if record.score is None and 200 <= record.word_count <= 500:
            return "review"
        return "archive"
    return "archive"


# ---- Build records ----

def build_records(discovered: list[dict]) -> list[FileRecord]:
    """Build FileRecord for each discovered file. Reads each file once (CTO issue #1)."""
    records = []
    read_errors = []

    for item in discovered:
        path = item["path"]

        try:
            text = path.read_text(errors="replace")
        except Exception as e:
            read_errors.append(f"{path.name}: {e}")
            text = ""

        meta = parse_metadata_from_text(text, path)
        word_count = len(text.split())
        struct_score = compute_structure_score(text)
        content_hash = hashlib.sha256(text[:2000].encode()).hexdigest()[:12]

        rec = FileRecord(
            path=str(path.relative_to(DATA_DIR)),
            filename=path.name,
            detection=item["detection"],
            title=meta.get("title", path.stem),
            created=meta.get("created", ""),
            score=meta.get("score"),
            status=meta.get("status", "unknown"),
            task_type=meta.get("task_type", ""),
            domain=detect_domain(meta.get("title", ""), text[:1000]),
            word_count=word_count,
            structure_score=struct_score,
            linked_files=find_linked_outputs(text) if "nightshift-exec-" in path.name else [],
            content_hash=content_hash,
            keywords=extract_keywords(text),
        )

        rec.file_type = classify_file_type(path.name, meta, text)
        rec.knowledge_score = compute_knowledge_score(rec)
        rec.category = route_file(rec)
        records.append(rec)

    if read_errors:
        print(f"  Read errors ({len(read_errors)}):")
        for e in read_errors[:5]:
            print(f"    - {e}")

    return records


# ---- Dedup ----

def dedup_records(records: list[FileRecord]) -> list[FileRecord]:
    """Mark duplicates within title groups.
    Uses content_hash to avoid false-positive dedup (Data issue #4)."""
    groups = defaultdict(list)
    no_title = []

    for rec in records:
        nt = normalize_title(rec.title)
        if nt:
            groups[nt].append(rec)
        else:
            no_title.append(rec)

    result = list(no_title)
    for title, group in groups.items():
        if len(group) == 1:
            result.append(group[0])
            continue

        # Group by file_type first (exec_report and deliverable are different, keep both)
        by_type = defaultdict(list)
        for r in group:
            by_type[r.file_type].append(r)

        for ft, ft_group in by_type.items():
            if len(ft_group) == 1:
                result.append(ft_group[0])
            else:
                # Content comparison: check if files are truly duplicates
                # Group by content_hash for exact-match dedup
                by_hash = defaultdict(list)
                for r in ft_group:
                    by_hash[r.content_hash].append(r)

                for content_hash, hash_group in by_hash.items():
                    if len(hash_group) == 1:
                        result.append(hash_group[0])
                    else:
                        sorted_g = sorted(
                            hash_group,
                            key=lambda r: (
                                0 if r.detection != "subdir" else 1,
                                -(r.score if r.score is not None else -1),
                            ),
                        )
                        result.append(sorted_g[0])
                        for dup in sorted_g[1:]:
                            dup.category = "duplicate"
                            result.append(dup)

    return result


# ---- Reconciliation ----

def reconcile(records: list[FileRecord]) -> list[str]:
    """Verify all files are classified and counts balance."""
    warnings = []
    total = len(records)
    by_category = Counter(r.category for r in records)
    cat_sum = sum(by_category.values())
    if cat_sum != total:
        warnings.append(f"Category sum {cat_sum} != total {total}")

    unclassified = [r for r in records if not r.category]
    if unclassified:
        warnings.append(f"{len(unclassified)} files have no category")

    all_filenames = {r.filename for r in records}
    for r in records:
        for link in r.linked_files:
            link_basename = Path(link).name if "/" in link else link
            if link_basename not in all_filenames and not link.startswith("nightshift-L"):
                # Classify: server-side path vs local path vs relative
                if link.startswith("/home/"):
                    prefix = "Server-side ref"
                elif link.startswith("/"):
                    try:
                        link = str(Path(link).relative_to(DATA_DIR))
                        prefix = "Orphaned link"
                    except ValueError:
                        prefix = "External path"
                else:
                    prefix = "Orphaned link"
                warnings.append(f"{prefix}: {r.filename} -> {link}")

    return warnings


# ---- Content-review scan ----

def scan_content_review() -> int:
    """Quick scan of content-review/ for nightshift references."""
    cr_dir = INBOX / "content-review"
    if not cr_dir.exists():
        return 0
    count = 0
    for f in cr_dir.rglob("*.md"):
        try:
            head = f.read_text(errors="replace")[:500]
            if any(m in head for m in FRONTMATTER_MARKERS):
                count += 1
        except Exception:
            pass
    return count


# ==== Subcommands ====

def cmd_scan():
    """Discover, classify, dedup, and output JSON."""
    print("Discovering nightshift files...")
    discovered, disc_warnings = discover_files()
    print(f"  Found {len(discovered)} files")

    by_detection = Counter(d["detection"] for d in discovered)
    for det, count in sorted(by_detection.items()):
        print(f"    {det}: {count}")
    if disc_warnings:
        print(f"  Discovery warnings: {len(disc_warnings)}")
        for w in disc_warnings[:5]:
            print(f"    - {w}")

    print("Building records (single-pass I/O)...")
    records = build_records(discovered)

    print("Deduplicating (content-hash aware)...")
    records = dedup_records(records)

    warnings = reconcile(records)
    if warnings:
        print(f"  Reconciliation warnings: {len(warnings)}")
        for w in warnings[:10]:
            print(f"    - {w}")

    by_type = Counter(r.file_type for r in records)
    by_domain = Counter(r.domain for r in records)
    by_category = Counter(r.category for r in records)
    duplicates = [r for r in records if r.category == "duplicate"]
    knowledge_candidates = [r for r in records if r.category == "knowledge"]

    dates = [r.created for r in records if r.created]
    date_range = {"min": min(dates) if dates else "", "max": max(dates) if dates else ""}

    cr_count = scan_content_review()

    now = datetime.now()
    run_id = now.strftime("%Y-%m-%d_%H%M%S")
    output = {
        "run_id": run_id,
        "scan_date": now.isoformat(),
        "total_files": len(records),
        "by_detection": dict(by_detection),
        "by_type": dict(by_type),
        "by_domain": dict(by_domain),
        "by_category": dict(by_category),
        "duplicates": len(duplicates),
        "reconciliation_warnings": warnings,
        "date_range": date_range,
        "content_review_nightshift_count": cr_count,
        "knowledge_candidates": len(knowledge_candidates),
        "files": [asdict(r) for r in records],
    }

    STATE_DIR.mkdir(parents=True, exist_ok=True)
    out_path = STATE_DIR / f"nightshift_scan_{run_id}.json"
    out_path.write_text(json.dumps(output, indent=2, default=str))

    # Rotate old scan files (keep last 5)
    old_scans = sorted(STATE_DIR.glob("nightshift_scan_*.json"), reverse=True)
    for stale in old_scans[5:]:
        stale.unlink()
        print(f"  Rotated old scan: {stale.name}")

    print(f"\nScan saved to: {out_path}")
    print(f"\nSummary:")
    print(f"  Total files:           {len(records)}")
    print(f"  By category:           {dict(by_category)}")
    print(f"  Knowledge candidates:  {len(knowledge_candidates)}")
    print(f"  Duplicates:            {len(duplicates)}")
    print(f"  Date range:            {date_range['min']} to {date_range['max']}")
    print(f"  Content-review refs:   {cr_count}")
    if warnings:
        print(f"  Warnings:              {len(warnings)}")

    return out_path


def _latest_scan() -> dict | None:
    """Load the most recent scan JSON. Returns None if no scan exists."""
    scans = sorted(STATE_DIR.glob("nightshift_scan_*.json"), reverse=True)
    if not scans:
        return None
    data = json.loads(scans[0].read_text())
    print(f"Using scan: {scans[0].name}")
    return data


def cmd_report():
    """Generate human-readable report from latest scan."""
    data = _latest_scan()
    if not data:
        print("No scan found. Run 'scan' first.")
        return
    files = data["files"]

    lines = []
    lines.append("# Nightshift Inbox Classification Report")
    lines.append("")
    lines.append(f"Scan: {data['scan_date'][:10]} | Files: {data['total_files']}")
    lines.append(f"Date range: {data['date_range']['min']} to {data['date_range']['max']}")
    lines.append("")

    # Category summary
    lines.append("## By Category")
    lines.append("")
    lines.append("| Category | Count |")
    lines.append("|----------|-------|")
    for cat, count in sorted(data["by_category"].items(), key=lambda x: -x[1]):
        lines.append(f"| {cat} | {count} |")
    lines.append("")

    # Type summary
    lines.append("## By File Type")
    lines.append("")
    lines.append("| Type | Count |")
    lines.append("|------|-------|")
    for ft, count in sorted(data["by_type"].items(), key=lambda x: -x[1]):
        lines.append(f"| {ft} | {count} |")
    lines.append("")

    # Domain summary
    lines.append("## By Domain")
    lines.append("")
    lines.append("| Domain | Count |")
    lines.append("|--------|-------|")
    for dom, count in sorted(data["by_domain"].items(), key=lambda x: -x[1]):
        lines.append(f"| {dom} | {count} |")
    lines.append("")

    # Detection method
    lines.append("## By Detection Method")
    lines.append("")
    lines.append("| Method | Count |")
    lines.append("|--------|-------|")
    for det, count in sorted(data["by_detection"].items(), key=lambda x: -x[1]):
        lines.append(f"| {det} | {count} |")
    lines.append("")

    # Knowledge candidates (top 30)
    knowledge = [f for f in files if f["category"] == "knowledge"]
    knowledge.sort(key=lambda f: f["knowledge_score"], reverse=True)
    lines.append(f"## Knowledge Candidates ({len(knowledge)} files)")
    lines.append("")
    if knowledge:
        lines.append("| # | File | Domain | Words | KScore | Title |")
        lines.append("|---|------|--------|-------|--------|-------|")
        for i, f in enumerate(knowledge[:30], 1):
            title = f["title"][:45]
            lines.append(f"| {i} | {f['filename'][:40]} | {f['domain']} | {f['word_count']} | {f['knowledge_score']:.3f} | {title} |")
        if len(knowledge) > 30:
            lines.append("")
            lines.append(f"... and {len(knowledge) - 30} more")
    lines.append("")

    # Failed tasks
    failed = [f for f in files if f["category"] == "failed"]
    lines.append(f"## Failed Tasks ({len(failed)} files)")
    lines.append("")
    if failed:
        lines.append("| File | Title |")
        lines.append("|------|-------|")
        for f in failed:
            lines.append(f"| {f['filename'][:45]} | {f['title'][:50]} |")
    lines.append("")

    # Duplicates
    dups = [f for f in files if f["category"] == "duplicate"]
    lines.append(f"## Duplicates ({len(dups)} files)")
    lines.append("")
    if dups:
        for f in dups:
            lines.append(f"- {f['filename']} ({f['file_type']})")
    lines.append("")

    # Review items
    review = [f for f in files if f["category"] == "review"]
    lines.append(f"## Review Required ({len(review)} files)")
    lines.append("")
    if review:
        lines.append("| File | Domain | Words | Title |")
        lines.append("|------|--------|-------|-------|")
        for f in review:
            lines.append(f"| {f['filename'][:40]} | {f['domain']} | {f['word_count']} | {f['title'][:45]} |")
    lines.append("")

    # Score distribution
    scored = [f for f in files if f["score"] is not None]
    if scored:
        lines.append(f"## Score Distribution ({len(scored)} scored files)")
        lines.append("")
        brackets = {"0.90+": 0, "0.80-0.89": 0, "0.70-0.79": 0, "0.60-0.69": 0, "<0.60": 0}
        for f in scored:
            s = f["score"]
            if s >= 0.90: brackets["0.90+"] += 1
            elif s >= 0.80: brackets["0.80-0.89"] += 1
            elif s >= 0.70: brackets["0.70-0.79"] += 1
            elif s >= 0.60: brackets["0.60-0.69"] += 1
            else: brackets["<0.60"] += 1
        lines.append("| Range | Count |")
        lines.append("|-------|-------|")
        for bracket, count in brackets.items():
            lines.append(f"| {bracket} | {count} |")
        lines.append("")

    # Reconciliation warnings
    if data["reconciliation_warnings"]:
        lines.append("## Warnings")
        lines.append("")
        for w in data["reconciliation_warnings"]:
            lines.append(f"- {w}")
        lines.append("")

    # Content-review info
    if data["content_review_nightshift_count"]:
        lines.append("## Content-Review References")
        lines.append("")
        lines.append(f"{data['content_review_nightshift_count']} files in content-review/ reference nightshift (not processed).")
        lines.append("")

    # Full file listing
    lines.append("## All Files")
    lines.append("")
    lines.append("| File | Date | Domain | Type | Score | Cat | Title |")
    lines.append("|------|------|--------|------|-------|-----|-------|")
    for f in sorted(files, key=lambda x: x.get("created", "")):
        score_str = f"{f['score']:.2f}" if f["score"] is not None else "----"
        title = f["title"][:35]
        lines.append(f"| {f['filename'][:35]} | {f['created'][:10]} | {f['domain'][:8]} | {f['file_type'][:10]} | {score_str} | {f['category'][:7]} | {title} |")

    report_text = "\n".join(lines)
    report_path = STATE_DIR / "nightshift_report.md"
    report_path.write_text(report_text)
    print(f"Report saved to: {report_path}")
    print(f"\nQuick summary:")
    print(f"  Total:      {data['total_files']}")
    print(f"  Knowledge:  {data['knowledge_candidates']}")
    print(f"  Archive:    {data['by_category'].get('archive', 0)}")
    print(f"  Failed:     {data['by_category'].get('failed', 0)}")
    print(f"  Review:     {data['by_category'].get('review', 0)}")
    print(f"  Duplicate:  {data['by_category'].get('duplicate', 0)}")


def cmd_archive(execute: bool = False):
    """Archive files based on scan classification."""
    data = _latest_scan()
    if not data:
        print("No scan found. Run 'scan' first.")
        return
    files = data["files"]

    mode = "EXECUTING" if execute else "DRY RUN"
    print(f"\n{'='*50}")
    print(f"  ARCHIVE {mode}")
    print(f"{'='*50}\n")

    moved = 0
    skipped = 0
    errors = 0
    error_details = []

    for f in files:
        cat = f["category"]

        src = DATA_DIR / f["path"]
        if not src.exists():
            continue

        if cat in ("archive", "knowledge", "duplicate"):
            dest = archive_path("0-personal", f["filename"], f["created"])
        elif cat == "failed":
            dest = ARCHIVE_BASE / "failed" / f["filename"]
        elif cat == "review":
            dest = INBOX / "review" / "nightshift" / f["filename"]
        else:
            continue

        if dest.exists():
            skipped += 1
            if not execute:
                print(f"  SKIP (exists): {f['filename']} -> {dest.relative_to(DATA_DIR)}")
            continue

        if execute:
            try:
                dest.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(str(src), str(dest))
                src.unlink()
                moved += 1
            except Exception as e:
                print(f"  ERROR: {f['filename']}: {e}")
                # If copy succeeded but unlink failed, dest exists — next run skips
                error_details.append({"filename": f["filename"], "error": str(e)})
                errors += 1
        else:
            print(f"  {cat:10s} {f['filename'][:45]:45s} -> {str(dest.relative_to(DATA_DIR))}")
            moved += 1

    print(f"\n{'='*50}")
    action = "Moved" if execute else "Would move"
    print(f"  {action}: {moved} files")
    print(f"  Skipped (already exists): {skipped}")
    if errors:
        print(f"  Errors: {errors}")
        # Persist errors for operational observability
        if execute:
            err_path = STATE_DIR / "archive_errors.json"
            err_path.write_text(json.dumps({"date": datetime.now().isoformat(), "errors": error_details}, indent=2))
            print(f"  Error details: {err_path}")
    print(f"{'='*50}")


def cmd_index():
    """Generate _manifest.yaml per month + _index.md in archive.
    Uses scan JSON data when available to avoid re-parsing (CTO issue #8)."""
    if not ARCHIVE_BASE.exists():
        print("Archive directory not found. Run 'archive --execute' first.")
        return

    # Try to load scan data for pre-computed metadata
    scan_lookup = {}
    scan_data = _latest_scan()
    if scan_data:
        for f in scan_data["files"]:
            scan_lookup[f["filename"]] = f
    else:
        print("  No scan data found, will parse files directly.")

    all_entries = []

    for month_dir in sorted(ARCHIVE_BASE.iterdir()):
        if not month_dir.is_dir() or month_dir.name.startswith("_"):
            continue

        entries = []
        for f in sorted(month_dir.glob("*.md")):
            if f.name.startswith("_"):
                continue

            # Use scan data if available, otherwise parse
            if f.name in scan_lookup:
                sd = scan_lookup[f.name]
                entry = {
                    "filename": f.name,
                    "title": sd.get("title", f.stem),
                    "score": sd.get("score"),
                    "domain": sd.get("domain", "personal"),
                    "file_type": sd.get("file_type", "deliverable"),
                    "keywords": sd.get("keywords", []),
                }
            else:
                text = f.read_text(errors="replace")
                meta = parse_metadata_from_text(text, f)
                entry = {
                    "filename": f.name,
                    "title": meta.get("title", f.stem),
                    "score": meta.get("score"),
                    "domain": detect_domain(meta.get("title", ""), text[:1000]),
                    "file_type": classify_file_type(f.name, meta, text),
                    "keywords": extract_keywords(text),
                }

            entries.append(entry)
            all_entries.append({**entry, "month": month_dir.name})

        if entries:
            manifest = {
                "generated": datetime.now().strftime("%Y-%m-%d"),
                "files": entries,
            }
            manifest_path = month_dir / "_manifest.yaml"
            manifest_path.write_text(yaml.dump(manifest, default_flow_style=False, allow_unicode=True))
            print(f"  Manifest: {month_dir.name}/ ({len(entries)} files)")

    # Handle failed/ directory
    failed_dir = ARCHIVE_BASE / "failed"
    if failed_dir.exists():
        for f in sorted(failed_dir.glob("*.md")):
            if f.name.startswith("_"):
                continue
            if f.name in scan_lookup:
                sd = scan_lookup[f.name]
                all_entries.append({
                    "filename": f.name,
                    "title": sd.get("title", f.stem),
                    "score": None,
                    "domain": sd.get("domain", "personal"),
                    "file_type": "failure",
                    "month": "failed",
                })
            else:
                text = f.read_text(errors="replace")
                meta = parse_metadata_from_text(text, f)
                all_entries.append({
                    "filename": f.name,
                    "title": meta.get("title", f.stem),
                    "score": None,
                    "domain": "personal",
                    "file_type": "failure",
                    "month": "failed",
                })

    # Generate _index.md
    lines = []
    lines.append("# Nightshift Archive Index")
    lines.append("")
    lines.append(f"Processed: {datetime.now().strftime('%Y-%m-%d')} | Files: {len(all_entries)}")
    lines.append("")

    months = Counter(e["month"] for e in all_entries)
    lines.append("## By Month")
    lines.append("")
    lines.append("| Month | Files |")
    lines.append("|-------|-------|")
    for month, count in sorted(months.items()):
        lines.append(f"| [{month}]({month}/) | {count} |")
    lines.append("")

    scored = [e for e in all_entries if e.get("score") is not None]
    scored.sort(key=lambda e: e["score"], reverse=True)
    if scored:
        lines.append("## Top 10 Highest-Value Outputs")
        lines.append("")
        lines.append("| File | Score | Domain | Title |")
        lines.append("|------|-------|--------|-------|")
        for e in scored[:10]:
            lines.append(f"| [{e['filename'][:35]}]({e['month']}/{e['filename']}) | {e['score']:.2f} | {e['domain']} | {e['title'][:40]} |")
        lines.append("")

    failed_entries = [e for e in all_entries if e["file_type"] == "failure"]
    if failed_entries:
        lines.append(f"## Failed Tasks ({len(failed_entries)})")
        lines.append("")
        lines.append("| File | Title |")
        lines.append("|------|-------|")
        for e in failed_entries:
            lines.append(f"| [{e['filename'][:40]}](failed/{e['filename']}) | {e['title'][:50]} |")
        lines.append("")

    lines.append("## All Files")
    lines.append("")
    lines.append("| File | Month | Domain | Score | Type | Keywords |")
    lines.append("|------|-------|--------|-------|------|----------|")
    for e in sorted(all_entries, key=lambda x: x.get("filename", "")):
        score_str = f"{e['score']:.2f}" if e.get("score") is not None else "----"
        kw = ", ".join(e.get("keywords", [])[:5])
        lines.append(f"| {e['filename'][:35]} | {e['month']} | {e['domain'][:8]} | {score_str} | {e['file_type'][:10]} | {kw} |")

    index_path = ARCHIVE_BASE / "_index.md"
    index_path.write_text("\n".join(lines))
    print(f"\nIndex saved to: {index_path}")
    print(f"Total archived files indexed: {len(all_entries)}")


# ---- Main ----

def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    cmd = sys.argv[1]

    if cmd == "scan":
        cmd_scan()
    elif cmd == "report":
        cmd_report()
    elif cmd == "archive":
        execute = "--execute" in sys.argv
        cmd_archive(execute=execute)
    elif cmd == "index":
        cmd_index()
    else:
        print(f"Unknown command: {cmd}")
        print("Available: scan, report, archive, index")
        sys.exit(1)


if __name__ == "__main__":
    main()
