"""
Post today's standup section from the personal journal as a comment on the
pinned standup issue in datafund/datafund-space#4.

Usage:
    python3 .datacore/lib/post_standup.py                   # post today's
    python3 .datacore/lib/post_standup.py --dry-run         # print what would post
    python3 .datacore/lib/post_standup.py --if-not-posted   # cron-safe; skip if already posted
    python3 .datacore/lib/post_standup.py --date 2026-05-11

Reads `## Standup` section from `0-personal/notes/journals/YYYY-MM-DD.md`
(generated by /today via the meetings:today-hook + standup-generator agent),
and posts it as a comment on the pinned issue using `gh issue comment`.

Use --if-not-posted from cron/launchd: it queries the issue's comments and
exits silently (rc=0) if today's date marker is already present.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from datetime import date, datetime
from pathlib import Path

REPO = "datafund/datafund-space"
ISSUE = 4
JOURNAL_DIR = Path(__file__).resolve().parent.parent.parent / "0-personal" / "notes" / "journals"


def extract_standup(journal_text: str) -> str | None:
    """Pull the ## Standup section out of the journal markdown."""
    pattern = re.compile(r"^##\s+Standup\b.*?(?=^##\s|\Z)", re.MULTILINE | re.DOTALL | re.IGNORECASE)
    match = pattern.search(journal_text)
    if not match:
        return None
    section = match.group(0).strip()
    section = re.sub(r"^##\s+Standup\b.*?$\n?", "", section, flags=re.MULTILINE | re.IGNORECASE, count=1)
    return section.strip()


def journal_path_for(d: date) -> Path:
    return JOURNAL_DIR / f"{d.isoformat()}.md"


def already_posted(target_date: date) -> bool:
    """Check existing issue comments for today's date marker (`**YYYY-MM-DD**`)."""
    marker = f"**{target_date.isoformat()}**"
    result = subprocess.run(
        ["gh", "issue", "view", str(ISSUE), "--repo", REPO,
         "--json", "comments", "--jq", ".comments[].body"],
        check=True, capture_output=True, text=True,
    )
    return marker in result.stdout


def post_comment(body: str) -> None:
    subprocess.run(
        ["gh", "issue", "comment", str(ISSUE), "--repo", REPO, "--body", body],
        check=True,
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Post today's standup to the pinned GitHub issue")
    parser.add_argument("--date", help="ISO date (default: today)")
    parser.add_argument("--dry-run", action="store_true", help="Print what would be posted, don't post")
    parser.add_argument("--if-not-posted", action="store_true",
                        help="Cron-safe: check existing comments first, skip silently if today is already posted")
    args = parser.parse_args()

    target_date = (
        datetime.strptime(args.date, "%Y-%m-%d").date() if args.date else date.today()
    )

    if args.if_not_posted:
        try:
            if already_posted(target_date):
                print(f"skip  {target_date.isoformat()} already posted to {REPO}#{ISSUE}")
                return 0
        except subprocess.CalledProcessError as exc:
            print(f"WARN  could not check existing comments: {exc}", file=sys.stderr)
            # Fall through and try to post anyway — better a duplicate than missing the standup

    journal = journal_path_for(target_date)
    if not journal.exists():
        print(f"No journal at {journal}", file=sys.stderr)
        return 1

    body_section = extract_standup(journal.read_text())
    if not body_section:
        print(f"No '## Standup' section in {journal}", file=sys.stderr)
        return 1

    comment = f"**{target_date.isoformat()}** ({target_date.strftime('%a')})\n\n{body_section}"

    if args.dry_run:
        print(f"--- would post to {REPO}#{ISSUE} ---")
        print(comment)
        return 0

    post_comment(comment)
    print(f"OK  posted standup for {target_date.isoformat()} to {REPO}#{ISSUE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
