"""
Post today's standup section from the personal journal as a comment on the
pinned standup issue in datafund/datafund-space#4.

Usage:
    python3 .datacore/lib/post_standup.py                   # post today's
    python3 .datacore/lib/post_standup.py --dry-run         # print what would post
    python3 .datacore/lib/post_standup.py --if-not-posted   # cron-safe; skip if already posted
    python3 .datacore/lib/post_standup.py --date 2026-05-11

Reads `## Standup` section from `0-personal/notes/journals/YYYY-MM-DD.md`
(generated by /today via the meetings:today-hook + standup-generator agent),
and posts it as a comment on the pinned issue using `gh issue comment`.

Use --if-not-posted from cron/launchd: it queries the issue's comments and
exits silently (rc=0) if today's date marker is already present.

Own space only (MEM-16): the personal journal's standup spans every space, and
this posts to the datafund team. Only 1-datafund's lines go out -- a line
tagged with another space (`[5-plur] ...`) or under another space's heading
(`### 5-plur -- @x`) is dropped, untagged lines outside a 1-datafund section
are dropped (fail closed) -- and a person's full name that is not a team
member (1-datafund/.datacore/config.yaml team.members) is replaced by
"an external contact". A full name is a known contact (a CRM people note,
*/3-knowledge/reference/people/<Name>.md) or a capitalised pair right after
with/to/from/by/met/call/cc.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from datetime import date, datetime
from pathlib import Path

REPO = "datafund/datafund-space"
ISSUE = 4
DATA_ROOT = Path(__file__).resolve().parent.parent.parent
JOURNAL_DIR = DATA_ROOT / "0-personal" / "notes" / "journals"

sys.path.insert(0, str(Path(__file__).resolve().parent))
from spaces import space_for  # noqa: E402

#: The team space the standup posts for (install.yaml roles.standup).
SPACE = space_for("standup", DATA_ROOT, "0-personal")
_SPACE_HEADING = re.compile(r"^#{1,6}\s+(\d+-[\w-]+)\b")
_HEADING = re.compile(r"^(#{1,6})\s")
_FULL_NAME = re.compile(r"\b([A-Z\u00C0-\u017D][a-z\u00DF-\u017E]+)\s+([A-Z\u00C0-\u017D][a-z\u00DF-\u017E]+)\b")
_PERSON_CONTEXT = re.compile(r"\b(?:with|to|from|by|met|meet|meeting|call|called|cc|thanks|asked|told)\s+$", re.I)


def known_contacts(root: Path = DATA_ROOT) -> set[str]:
    """Full names of people with a CRM note, lowercased."""
    return {p.stem.lower() for p in root.glob("*/3-knowledge/reference/people/*.md")}


def extract_standup(journal_text: str) -> str | None:
    """Pull the ## Standup section out of the journal markdown."""
    pattern = re.compile(r"^##\s+Standup\b.*?(?=^##\s|\Z)", re.MULTILINE | re.DOTALL | re.IGNORECASE)
    match = pattern.search(journal_text)
    if not match:
        return None
    section = match.group(0).strip()
    section = re.sub(r"^##\s+Standup\b.*?$\n?", "", section, flags=re.MULTILINE | re.IGNORECASE, count=1)
    return section.strip()


def team_names(space_dir: Path) -> set[str]:
    """Names, ids and GitHub handles of the space's team members (lowercased)."""
    try:
        import yaml
        cfg = yaml.safe_load((space_dir / ".datacore" / "config.yaml").read_text()) or {}
    except Exception:  # noqa: BLE001 -- no roster: nobody is a member
        return set()
    names = set()
    for m in ((cfg.get("team") or {}).get("members") or []):
        if isinstance(m, dict):
            for key in ("id", "name", "github"):
                if m.get(key):
                    names.update(str(m[key]).lower().split())
        elif m:
            names.add(str(m).lower())
    return names


def _prune_empty_headings(lines: list[str]) -> list[str]:
    """Drop headings left with no content under them."""
    changed = True
    while changed:
        changed = False
        for i, line in enumerate(lines):
            h = _HEADING.match(line)
            if not h:
                continue
            rest = [l for l in lines[i + 1:] if l.strip()]
            nxt = _HEADING.match(rest[0]) if rest else None
            if not rest or (nxt and len(nxt.group(1)) <= len(h.group(1))):
                del lines[i]
                changed = True
                break
    return lines


def own_space_only(section: str, space: str = SPACE, members: set[str] | None = None,
                   contacts: set[str] | None = None) -> str:
    """The lines of a multi-space standup that belong to ``space``, outsiders unnamed."""
    from standup_inputs import space_tag
    members = members or set()
    current = None
    out: list[str] = []
    for line in section.splitlines():
        m = _SPACE_HEADING.match(line)
        if m:
            current = m.group(1)
            if current == space:
                out.append(line)
            continue
        if _HEADING.match(line) or not line.strip():
            out.append(line)
            continue
        tag = space_tag(line)
        if tag is not None:
            if tag == space:
                out.append(re.sub(r"\[" + re.escape(tag) + r"\]\s*", "", line, count=1))
        elif current == space:
            out.append(line)
    text = "\n".join(_prune_empty_headings(out))

    contacts = contacts if contacts is not None else known_contacts()

    def unname(m: re.Match) -> str:
        first, last = m.group(1).lower(), m.group(2).lower()
        if first in members or last in members:
            return m.group(0)
        person = (f"{first} {last}" in contacts
                  or _PERSON_CONTEXT.search(m.string[max(0, m.start() - 12):m.start()]))
        return "an external contact" if person else m.group(0)

    text = _FULL_NAME.sub(unname, text)
    return re.sub(r"\n{3,}", "\n\n", text).strip()


def journal_path_for(d: date) -> Path:
    return JOURNAL_DIR / f"{d.isoformat()}.md"


def already_posted(target_date: date) -> bool:
    """Check existing issue comments for today's date marker (`**YYYY-MM-DD**`)."""
    marker = f"**{target_date.isoformat()}**"
    result = subprocess.run(
        ["gh", "issue", "view", str(ISSUE), "--repo", REPO,
         "--json", "comments", "--jq", ".comments[].body"],
        check=True, capture_output=True, text=True,
    )
    return marker in result.stdout


def post_comment(body: str) -> None:
    subprocess.run(
        ["gh", "issue", "comment", str(ISSUE), "--repo", REPO, "--body", body],
        check=True,
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Post today's standup to the pinned GitHub issue")
    parser.add_argument("--date", help="ISO date (default: today)")
    parser.add_argument("--dry-run", action="store_true", help="Print what would be posted, don't post")
    parser.add_argument("--if-not-posted", action="store_true",
                        help="Cron-safe: check existing comments first, skip silently if today is already posted")
    args = parser.parse_args()

    target_date = (
        datetime.strptime(args.date, "%Y-%m-%d").date() if args.date else date.today()
    )

    if args.if_not_posted:
        try:
            if already_posted(target_date):
                print(f"skip  {target_date.isoformat()} already posted to {REPO}#{ISSUE}")
                return 0
        except subprocess.CalledProcessError as exc:
            print(f"WARN  could not check existing comments: {exc}", file=sys.stderr)
            # Fall through and try to post anyway — better a duplicate than missing the standup

    journal = journal_path_for(target_date)
    if not journal.exists():
        print(f"No journal at {journal}", file=sys.stderr)
        return 1

    body_section = extract_standup(journal.read_text())
    if not body_section:
        print(f"No '## Standup' section in {journal}", file=sys.stderr)
        return 1

    body_section = own_space_only(body_section, SPACE, team_names(DATA_ROOT / SPACE))
    if not body_section:
        print(f"skip  no {SPACE} lines in the standup of {journal}")
        return 0

    comment = f"**{target_date.isoformat()}** ({target_date.strftime('%a')})\n\n{body_section}"

    if args.dry_run:
        print(f"--- would post to {REPO}#{ISSUE} ---")
        print(comment)
        return 0

    post_comment(comment)
    print(f"OK  posted standup for {target_date.isoformat()} to {REPO}#{ISSUE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
