#!/usr/bin/env bash
# Build the Firm's public page and put it on testnet.datacore.one.
#
# WHAT THIS NEEDS FROM YOU, once:
#
#   1. DNS      testnet.datacore.one  A  209.38.243.88
#              (datacore.one already resolves there; testnet does not resolve
#               at all as of 2026-09-20.)
#
#   2. SSH      that box is NOT in .datacore/registry/infrastructure.yaml, so
#              this script has no alias to use. Set TESTNET_HOST to whatever
#              reaches it, e.g.
#                   export TESTNET_HOST=deploy@209.38.243.88
#              and add it to the registry so the next person does not have to
#              rediscover it.
#
#   3. A vhost  serving TESTNET_DOCROOT over TLS for that name. Whatever is
#              already serving datacore.one is almost certainly the thing to
#              extend; this script does not touch web-server config, because
#              guessing at someone else's nginx from a laptop is how a working
#              site goes down.
#
# WHAT IT REFUSES TO DO. The page is generated by testnet_dashboard.py, which
# audits its own output against this installation's real registries -- every
# principal, every host, every space name, any address, any version string --
# and writes nothing if one survives. This script checks that exit code and
# stops. A stale page that is clean beats a fresh page that leaks, so a failed
# audit leaves whatever is currently published exactly where it is.
set -uo pipefail

LIB="${DATACORE_LIB:-$HOME/Data/.datacore/lib}"
PY="${DATACORE_PYTHON:-python3}"
BUILD="${TESTNET_BUILD:-${TMPDIR:-/tmp}/testnet-build}"
DOCROOT="${TESTNET_DOCROOT:-/var/www/testnet.datacore.one}"

mkdir -p "$BUILD"

echo "── building"
if ! "$PY" "$LIB/testnet_dashboard.py" --out "$BUILD/index.html"; then
  echo "REFUSED: the page did not pass its own disclosure audit; nothing deployed." >&2
  echo "Whatever is currently published is untouched." >&2
  exit 1
fi

# Belt and braces: audit the file that is about to be copied, not just the one
# that was generated. They are the same file today. They would not be if
# anything ever wrote into $BUILD between the two steps, and the whole point of
# this check is that it does not depend on that staying true.
echo "── auditing the built file"
if ! "$PY" "$LIB/testnet_dashboard.py" --audit-only "$BUILD/index.html"; then
  echo "REFUSED: the built file did not pass the audit; nothing deployed." >&2
  exit 1
fi

if [ "${1:-}" = "--build-only" ]; then
  echo "built: $BUILD/index.html (not deployed; --build-only)"
  exit 0
fi

if [ -z "${TESTNET_HOST:-}" ]; then
  cat >&2 <<'MSG'

Not deployed: TESTNET_HOST is unset, and this script will not guess at a host.

The page is built and audited. To publish it:

    export TESTNET_HOST=<user>@209.38.243.88
    .datacore/lib/testnet_deploy.sh

MSG
  echo "built: $BUILD/index.html"
  exit 2
fi

echo "── deploying to $TESTNET_HOST:$DOCROOT"
rsync -az --delete "$BUILD/" "$TESTNET_HOST:$DOCROOT/"
rc=$?
if [ $rc -ne 0 ]; then
  echo "rsync failed (rc=$rc)" >&2
  exit $rc
fi
echo "deployed: https://testnet.datacore.one"
